/// Per-property capability-level metadata for the inspector.
///
/// The studio inspector consults this to decide which properties to reveal at
/// the user's chosen level. Basic mode shows only "safe" knobs (colour, label,
/// limits); Advanced adds layout/bindings; Expert exposes everything including
/// raw transform values and graph bindings.
library;

import 'package:dashboard_model/dashboard_model.dart';

/// Categories for grouping widget properties in the property inspector.
enum PropertyCategory {
  visuals('Visuals'),
  dataBindings('Data Bindings'),
  layoutAndSpacing('Layout & Spacing'),
  fontsAndColors('Fonts & Colors');

  final String label;
  const PropertyCategory(this.label);

  String get displayName => label;
}

/// Metadata for a single widget property.
class PropertyMeta {
  final String key;
  final CapabilityLevel minLevel;
  final String label;
  final bool safe;
  final PropertyCategory category;
  final double? min;
  final double? max;
  final double? step;

  const PropertyMeta({
    required this.key,
    required this.minLevel,
    required this.label,
    this.safe = false,
    this.category = PropertyCategory.visuals,
    this.min,
    this.max,
    this.step,
  });
}

/// OOP wrapper for widget property manifest definitions.
class WidgetManifest {
  final String kind;
  const WidgetManifest(this.kind);

  static WidgetManifest forKind(String kind) => WidgetManifest(kind);

  List<PropertyMeta> get properties => allProperties(kind);

  Map<PropertyCategory, List<PropertyMeta>> propertiesByCategory(
          {CapabilityLevel? level}) =>
      _groupPropertiesByCategory(kind, level: level);

  Map<PropertyCategory, List<PropertyMeta>> get categorizedProperties =>
      propertiesByCategory();

  List<PropertyMeta> getPropertiesByCategory(PropertyCategory category,
          {CapabilityLevel? level}) =>
      (_groupPropertiesByCategory(kind, level: level)[category] ??
          const <PropertyMeta>[]);
}

const List<PropertyMeta> _gauge = [
  PropertyMeta(
      key: 'value',
      minLevel: CapabilityLevel.advanced,
      label: 'Value',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'min',
      minLevel: CapabilityLevel.basic,
      label: 'Minimum',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'max',
      minLevel: CapabilityLevel.basic,
      label: 'Maximum',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'label',
      minLevel: CapabilityLevel.basic,
      label: 'Label',
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'unit',
      minLevel: CapabilityLevel.basic,
      label: 'Unit',
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'color',
      minLevel: CapabilityLevel.basic,
      label: 'Colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'accent',
      minLevel: CapabilityLevel.advanced,
      label: 'Accent',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'tickCount',
      minLevel: CapabilityLevel.advanced,
      label: 'Ticks',
      category: PropertyCategory.visuals,
      min: 2,
      max: 50,
      step: 1),
  PropertyMeta(
      key: 'sweepAngle',
      minLevel: CapabilityLevel.advanced,
      label: 'Sweep',
      category: PropertyCategory.visuals,
      min: 10,
      max: 360,
      step: 5),
  PropertyMeta(
      key: 'startAngle',
      minLevel: CapabilityLevel.advanced,
      label: 'Start angle',
      category: PropertyCategory.visuals,
      min: 0,
      max: 360,
      step: 5),
  PropertyMeta(
      key: 'arcWidth',
      minLevel: CapabilityLevel.advanced,
      label: 'Arc width',
      category: PropertyCategory.visuals,
      min: 1,
      max: 50,
      step: 1),
  PropertyMeta(
      key: 'needleStyle',
      minLevel: CapabilityLevel.advanced,
      label: 'Needle',
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'showCenterText',
      minLevel: CapabilityLevel.basic,
      label: 'Center text',
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'centerValue',
      minLevel: CapabilityLevel.advanced,
      label: 'Center value',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'centerUnit',
      minLevel: CapabilityLevel.basic,
      label: 'Center unit',
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'subLabel',
      minLevel: CapabilityLevel.basic,
      label: 'Sub-label',
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'showTickLabels',
      minLevel: CapabilityLevel.basic,
      label: 'Tick labels',
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'innerValue',
      minLevel: CapabilityLevel.advanced,
      label: 'Inner value',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'innerMin',
      minLevel: CapabilityLevel.advanced,
      label: 'Inner min',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'innerMax',
      minLevel: CapabilityLevel.advanced,
      label: 'Inner max',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'innerColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Inner colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'innerArcWidth',
      minLevel: CapabilityLevel.advanced,
      label: 'Inner arc',
      category: PropertyCategory.visuals,
      min: 1,
      max: 30,
      step: 1),
  PropertyMeta(
      key: 'redlineStart',
      minLevel: CapabilityLevel.advanced,
      label: 'Redline',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'redlineColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Redline colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'backgroundColor',
      minLevel: CapabilityLevel.basic,
      label: 'Background',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'borderRadius',
      minLevel: CapabilityLevel.advanced,
      label: 'Radius',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 48,
      step: 1),
  PropertyMeta(
      key: 'fontSize',
      minLevel: CapabilityLevel.basic,
      label: 'Font size',
      category: PropertyCategory.fontsAndColors,
      min: 8,
      max: 96,
      step: 1),
  PropertyMeta(
      key: 'fontFamily',
      minLevel: CapabilityLevel.basic,
      label: 'Font family',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'fontWeight',
      minLevel: CapabilityLevel.basic,
      label: 'Font weight',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'letterSpacing',
      minLevel: CapabilityLevel.advanced,
      label: 'Letter spacing',
      category: PropertyCategory.fontsAndColors,
      min: -2,
      max: 10,
      step: 0.5),
  PropertyMeta(
      key: 'borderWidth',
      minLevel: CapabilityLevel.advanced,
      label: 'Border width',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 20,
      step: 0.5),
  PropertyMeta(
      key: 'borderColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Border colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowBlur',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow blur',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 40,
      step: 1),
  PropertyMeta(
      key: 'shadowOffsetY',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow Y',
      category: PropertyCategory.layoutAndSpacing,
      min: -20,
      max: 20,
      step: 1),
  PropertyMeta(
      key: 'opacity',
      minLevel: CapabilityLevel.advanced,
      label: 'Opacity',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 1,
      step: 0.05),
  PropertyMeta(
      key: 'padding',
      minLevel: CapabilityLevel.basic,
      label: 'Padding',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 64,
      step: 1),
  PropertyMeta(
      key: 'width',
      minLevel: CapabilityLevel.basic,
      label: 'Width',
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'height',
      minLevel: CapabilityLevel.basic,
      label: 'Height',
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'visible',
      minLevel: CapabilityLevel.basic,
      label: 'Visible',
      category: PropertyCategory.layoutAndSpacing),
];

const List<PropertyMeta> _bar = [
  PropertyMeta(
      key: 'value',
      minLevel: CapabilityLevel.advanced,
      label: 'Value binding',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'min',
      minLevel: CapabilityLevel.basic,
      label: 'Minimum',
      safe: true,
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'max',
      minLevel: CapabilityLevel.basic,
      label: 'Maximum',
      safe: true,
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'color',
      minLevel: CapabilityLevel.basic,
      label: 'Colour',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'orientation',
      minLevel: CapabilityLevel.advanced,
      label: 'Orientation',
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'showValue',
      minLevel: CapabilityLevel.basic,
      label: 'Show value',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'gradient',
      minLevel: CapabilityLevel.advanced,
      label: 'Gradient fill',
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'gradientColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Gradient colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'backgroundColor',
      minLevel: CapabilityLevel.basic,
      label: 'Background',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'borderRadius',
      minLevel: CapabilityLevel.advanced,
      label: 'Corner radius',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 48,
      step: 1),
  PropertyMeta(
      key: 'barRadius',
      minLevel: CapabilityLevel.advanced,
      label: 'Bar fill radius',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 48,
      step: 1),
  PropertyMeta(
      key: 'fontSize',
      minLevel: CapabilityLevel.basic,
      label: 'Font size',
      safe: true,
      category: PropertyCategory.fontsAndColors,
      min: 8,
      max: 96,
      step: 1),
  PropertyMeta(
      key: 'borderWidth',
      minLevel: CapabilityLevel.advanced,
      label: 'Border width',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 20,
      step: 0.5),
  PropertyMeta(
      key: 'borderColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Border colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowBlur',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow blur',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 40,
      step: 1),
  PropertyMeta(
      key: 'shadowOffsetY',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow offset Y',
      category: PropertyCategory.layoutAndSpacing,
      min: -20,
      max: 20,
      step: 1),
  PropertyMeta(
      key: 'opacity',
      minLevel: CapabilityLevel.advanced,
      label: 'Opacity',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 1,
      step: 0.05),
  PropertyMeta(
      key: 'padding',
      minLevel: CapabilityLevel.basic,
      label: 'Padding',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 64,
      step: 1),
  PropertyMeta(
      key: 'width',
      minLevel: CapabilityLevel.basic,
      label: 'Width',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'height',
      minLevel: CapabilityLevel.basic,
      label: 'Height',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'visible',
      minLevel: CapabilityLevel.basic,
      label: 'Visible',
      safe: true,
      category: PropertyCategory.layoutAndSpacing),
];

const List<PropertyMeta> _text = [
  PropertyMeta(
      key: 'value',
      minLevel: CapabilityLevel.advanced,
      label: 'Value binding',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'label',
      minLevel: CapabilityLevel.basic,
      label: 'Label',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'unit',
      minLevel: CapabilityLevel.basic,
      label: 'Unit',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'color',
      minLevel: CapabilityLevel.basic,
      label: 'Colour',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'backgroundColor',
      minLevel: CapabilityLevel.basic,
      label: 'Background',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'borderRadius',
      minLevel: CapabilityLevel.advanced,
      label: 'Corner radius',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 48,
      step: 1),
  PropertyMeta(
      key: 'fontSize',
      minLevel: CapabilityLevel.basic,
      label: 'Font size',
      safe: true,
      category: PropertyCategory.fontsAndColors,
      min: 8,
      max: 96,
      step: 1),
  PropertyMeta(
      key: 'fontFamily',
      minLevel: CapabilityLevel.basic,
      label: 'Font family',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'fontWeight',
      minLevel: CapabilityLevel.basic,
      label: 'Font weight',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'letterSpacing',
      minLevel: CapabilityLevel.advanced,
      label: 'Letter spacing',
      category: PropertyCategory.fontsAndColors,
      min: -2,
      max: 10,
      step: 0.5),
  PropertyMeta(
      key: 'borderWidth',
      minLevel: CapabilityLevel.advanced,
      label: 'Border width',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 20,
      step: 0.5),
  PropertyMeta(
      key: 'borderColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Border colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowBlur',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow blur',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 40,
      step: 1),
  PropertyMeta(
      key: 'shadowOffsetY',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow offset Y',
      category: PropertyCategory.layoutAndSpacing,
      min: -20,
      max: 20,
      step: 1),
  PropertyMeta(
      key: 'opacity',
      minLevel: CapabilityLevel.advanced,
      label: 'Opacity',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 1,
      step: 0.05),
  PropertyMeta(
      key: 'padding',
      minLevel: CapabilityLevel.basic,
      label: 'Padding',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 64,
      step: 1),
  PropertyMeta(
      key: 'width',
      minLevel: CapabilityLevel.basic,
      label: 'Width',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'height',
      minLevel: CapabilityLevel.basic,
      label: 'Height',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'visible',
      minLevel: CapabilityLevel.basic,
      label: 'Visible',
      safe: true,
      category: PropertyCategory.layoutAndSpacing),
];

const List<PropertyMeta> _status = [
  PropertyMeta(
      key: 'fault',
      minLevel: CapabilityLevel.advanced,
      label: 'Fault binding',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'label',
      minLevel: CapabilityLevel.basic,
      label: 'Label',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'value',
      minLevel: CapabilityLevel.advanced,
      label: 'State text',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'backgroundColor',
      minLevel: CapabilityLevel.basic,
      label: 'Background',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'borderRadius',
      minLevel: CapabilityLevel.advanced,
      label: 'Corner radius',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 48,
      step: 1),
  PropertyMeta(
      key: 'fontSize',
      minLevel: CapabilityLevel.basic,
      label: 'Font size',
      safe: true,
      category: PropertyCategory.fontsAndColors,
      min: 8,
      max: 96,
      step: 1),
  PropertyMeta(
      key: 'fontFamily',
      minLevel: CapabilityLevel.basic,
      label: 'Font family',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'fontWeight',
      minLevel: CapabilityLevel.basic,
      label: 'Font weight',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'letterSpacing',
      minLevel: CapabilityLevel.advanced,
      label: 'Letter spacing',
      category: PropertyCategory.fontsAndColors,
      min: -2,
      max: 10,
      step: 0.5),
  PropertyMeta(
      key: 'borderWidth',
      minLevel: CapabilityLevel.advanced,
      label: 'Border width',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 20,
      step: 0.5),
  PropertyMeta(
      key: 'borderColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Border colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowBlur',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow blur',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 40,
      step: 1),
  PropertyMeta(
      key: 'shadowOffsetY',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow offset Y',
      category: PropertyCategory.layoutAndSpacing,
      min: -20,
      max: 20,
      step: 1),
  PropertyMeta(
      key: 'opacity',
      minLevel: CapabilityLevel.advanced,
      label: 'Opacity',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 1,
      step: 0.05),
  PropertyMeta(
      key: 'padding',
      minLevel: CapabilityLevel.basic,
      label: 'Padding',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 64,
      step: 1),
  PropertyMeta(
      key: 'width',
      minLevel: CapabilityLevel.basic,
      label: 'Width',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'height',
      minLevel: CapabilityLevel.basic,
      label: 'Height',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'visible',
      minLevel: CapabilityLevel.basic,
      label: 'Visible',
      safe: true,
      category: PropertyCategory.layoutAndSpacing),
];

const List<PropertyMeta> _chart = [
  PropertyMeta(
      key: 'value',
      minLevel: CapabilityLevel.advanced,
      label: 'Value binding',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'min',
      minLevel: CapabilityLevel.basic,
      label: 'Y minimum',
      safe: true,
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'max',
      minLevel: CapabilityLevel.basic,
      label: 'Y maximum',
      safe: true,
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'window',
      minLevel: CapabilityLevel.advanced,
      label: 'Sample window',
      category: PropertyCategory.visuals,
      min: 10,
      max: 600,
      step: 10),
  PropertyMeta(
      key: 'label',
      minLevel: CapabilityLevel.basic,
      label: 'Label',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'unit',
      minLevel: CapabilityLevel.basic,
      label: 'Unit',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'color',
      minLevel: CapabilityLevel.basic,
      label: 'Colour',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'lineWidth',
      minLevel: CapabilityLevel.advanced,
      label: 'Line width',
      category: PropertyCategory.visuals,
      min: 0.5,
      max: 10,
      step: 0.5),
  PropertyMeta(
      key: 'showGrid',
      minLevel: CapabilityLevel.basic,
      label: 'Show grid',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'gridColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Grid colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'smoothCurve',
      minLevel: CapabilityLevel.advanced,
      label: 'Smooth curve',
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'fillArea',
      minLevel: CapabilityLevel.advanced,
      label: 'Fill area',
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'fillColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Fill colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'backgroundColor',
      minLevel: CapabilityLevel.basic,
      label: 'Background',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'borderRadius',
      minLevel: CapabilityLevel.advanced,
      label: 'Corner radius',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 48,
      step: 1),
  PropertyMeta(
      key: 'fontSize',
      minLevel: CapabilityLevel.basic,
      label: 'Font size',
      safe: true,
      category: PropertyCategory.fontsAndColors,
      min: 8,
      max: 96,
      step: 1),
  PropertyMeta(
      key: 'fontFamily',
      minLevel: CapabilityLevel.basic,
      label: 'Font family',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'fontWeight',
      minLevel: CapabilityLevel.basic,
      label: 'Font weight',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'letterSpacing',
      minLevel: CapabilityLevel.advanced,
      label: 'Letter spacing',
      category: PropertyCategory.fontsAndColors,
      min: -2,
      max: 10,
      step: 0.5),
  PropertyMeta(
      key: 'borderWidth',
      minLevel: CapabilityLevel.advanced,
      label: 'Border width',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 20,
      step: 0.5),
  PropertyMeta(
      key: 'borderColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Border colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowBlur',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow blur',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 40,
      step: 1),
  PropertyMeta(
      key: 'shadowOffsetY',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow offset Y',
      category: PropertyCategory.layoutAndSpacing,
      min: -20,
      max: 20,
      step: 1),
  PropertyMeta(
      key: 'opacity',
      minLevel: CapabilityLevel.advanced,
      label: 'Opacity',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 1,
      step: 0.05),
  PropertyMeta(
      key: 'padding',
      minLevel: CapabilityLevel.basic,
      label: 'Padding',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 64,
      step: 1),
  PropertyMeta(
      key: 'width',
      minLevel: CapabilityLevel.basic,
      label: 'Width',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'height',
      minLevel: CapabilityLevel.basic,
      label: 'Height',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'visible',
      minLevel: CapabilityLevel.basic,
      label: 'Visible',
      safe: true,
      category: PropertyCategory.layoutAndSpacing),
];

const List<PropertyMeta> _image = [
  PropertyMeta(
      key: 'src',
      minLevel: CapabilityLevel.basic,
      label: 'Image source',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'fit',
      minLevel: CapabilityLevel.advanced,
      label: 'Fit mode',
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'tint',
      minLevel: CapabilityLevel.basic,
      label: 'Tint',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'opacity',
      minLevel: CapabilityLevel.advanced,
      label: 'Opacity',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 1,
      step: 0.05),
  PropertyMeta(
      key: 'borderRadius',
      minLevel: CapabilityLevel.advanced,
      label: 'Corner radius',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 48,
      step: 1),
  PropertyMeta(
      key: 'borderWidth',
      minLevel: CapabilityLevel.advanced,
      label: 'Border width',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 20,
      step: 0.5),
  PropertyMeta(
      key: 'borderColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Border colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowBlur',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow blur',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 40,
      step: 1),
  PropertyMeta(
      key: 'shadowOffsetY',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow offset Y',
      category: PropertyCategory.layoutAndSpacing,
      min: -20,
      max: 20,
      step: 1),
  PropertyMeta(
      key: 'padding',
      minLevel: CapabilityLevel.basic,
      label: 'Padding',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 64,
      step: 1),
  PropertyMeta(
      key: 'width',
      minLevel: CapabilityLevel.basic,
      label: 'Width',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'height',
      minLevel: CapabilityLevel.basic,
      label: 'Height',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
];

const List<PropertyMeta> _web = [
  PropertyMeta(
      key: 'url',
      minLevel: CapabilityLevel.basic,
      label: 'URL',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'title',
      minLevel: CapabilityLevel.basic,
      label: 'Title',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'js',
      minLevel: CapabilityLevel.advanced,
      label: 'JavaScript enabled',
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'backgroundColor',
      minLevel: CapabilityLevel.basic,
      label: 'Background',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'borderRadius',
      minLevel: CapabilityLevel.advanced,
      label: 'Corner radius',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 48,
      step: 1),
  PropertyMeta(
      key: 'borderWidth',
      minLevel: CapabilityLevel.advanced,
      label: 'Border width',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 20,
      step: 0.5),
  PropertyMeta(
      key: 'borderColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Border colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowBlur',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow blur',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 40,
      step: 1),
  PropertyMeta(
      key: 'shadowOffsetY',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow offset Y',
      category: PropertyCategory.layoutAndSpacing,
      min: -20,
      max: 20,
      step: 1),
  PropertyMeta(
      key: 'padding',
      minLevel: CapabilityLevel.basic,
      label: 'Padding',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 64,
      step: 1),
  PropertyMeta(
      key: 'width',
      minLevel: CapabilityLevel.basic,
      label: 'Width',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'height',
      minLevel: CapabilityLevel.basic,
      label: 'Height',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'visible',
      minLevel: CapabilityLevel.basic,
      label: 'Visible',
      safe: true,
      category: PropertyCategory.layoutAndSpacing),
];

const List<PropertyMeta> _paint = [
  PropertyMeta(
      key: 'program',
      minLevel: CapabilityLevel.expert,
      label: 'Paint program (DSL)',
      category: PropertyCategory.visuals),
];

const List<PropertyMeta> _digitalspeed = [
  PropertyMeta(
      key: 'value',
      minLevel: CapabilityLevel.advanced,
      label: 'Value binding',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'unit',
      minLevel: CapabilityLevel.basic,
      label: 'Unit',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'sourceUnit',
      minLevel: CapabilityLevel.advanced,
      label: 'Source unit (kmh/mph/ms)',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'displayUnit',
      minLevel: CapabilityLevel.basic,
      label: 'Display unit (kmh/mph/ms)',
      safe: true,
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'color',
      minLevel: CapabilityLevel.basic,
      label: 'Colour',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'accent',
      minLevel: CapabilityLevel.advanced,
      label: 'Accent colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'showUnit',
      minLevel: CapabilityLevel.basic,
      label: 'Show unit',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'subLabel',
      minLevel: CapabilityLevel.basic,
      label: 'Sub-label',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'subValue',
      minLevel: CapabilityLevel.advanced,
      label: 'Sub-value',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'backgroundColor',
      minLevel: CapabilityLevel.basic,
      label: 'Background',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'borderRadius',
      minLevel: CapabilityLevel.advanced,
      label: 'Corner radius',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 48,
      step: 1),
  PropertyMeta(
      key: 'fontSize',
      minLevel: CapabilityLevel.basic,
      label: 'Font size',
      safe: true,
      category: PropertyCategory.fontsAndColors,
      min: 8,
      max: 96,
      step: 1),
  PropertyMeta(
      key: 'fontFamily',
      minLevel: CapabilityLevel.basic,
      label: 'Font family',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'fontWeight',
      minLevel: CapabilityLevel.basic,
      label: 'Font weight',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'letterSpacing',
      minLevel: CapabilityLevel.advanced,
      label: 'Letter spacing',
      category: PropertyCategory.fontsAndColors,
      min: -2,
      max: 10,
      step: 0.5),
  PropertyMeta(
      key: 'borderWidth',
      minLevel: CapabilityLevel.advanced,
      label: 'Border width',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 20,
      step: 0.5),
  PropertyMeta(
      key: 'borderColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Border colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowBlur',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow blur',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 40,
      step: 1),
  PropertyMeta(
      key: 'shadowOffsetY',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow offset Y',
      category: PropertyCategory.layoutAndSpacing,
      min: -20,
      max: 20,
      step: 1),
  PropertyMeta(
      key: 'opacity',
      minLevel: CapabilityLevel.advanced,
      label: 'Opacity',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 1,
      step: 0.05),
  PropertyMeta(
      key: 'padding',
      minLevel: CapabilityLevel.basic,
      label: 'Padding',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 64,
      step: 1),
  PropertyMeta(
      key: 'width',
      minLevel: CapabilityLevel.basic,
      label: 'Width',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'height',
      minLevel: CapabilityLevel.basic,
      label: 'Height',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'visible',
      minLevel: CapabilityLevel.basic,
      label: 'Visible',
      safe: true,
      category: PropertyCategory.layoutAndSpacing),
];

const List<PropertyMeta> _music = [
  PropertyMeta(
      key: 'title',
      minLevel: CapabilityLevel.basic,
      label: 'Track title',
      safe: true,
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'artist',
      minLevel: CapabilityLevel.basic,
      label: 'Artist',
      safe: true,
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'album',
      minLevel: CapabilityLevel.advanced,
      label: 'Album',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'progress',
      minLevel: CapabilityLevel.advanced,
      label: 'Progress (s)',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'duration',
      minLevel: CapabilityLevel.advanced,
      label: 'Duration (s)',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'showControls',
      minLevel: CapabilityLevel.basic,
      label: 'Show controls',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'color',
      minLevel: CapabilityLevel.basic,
      label: 'Colour',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'accent',
      minLevel: CapabilityLevel.advanced,
      label: 'Accent colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'albumColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Album art colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'backgroundColor',
      minLevel: CapabilityLevel.basic,
      label: 'Background',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'borderRadius',
      minLevel: CapabilityLevel.advanced,
      label: 'Corner radius',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 48,
      step: 1),
  PropertyMeta(
      key: 'fontSize',
      minLevel: CapabilityLevel.basic,
      label: 'Font size',
      safe: true,
      category: PropertyCategory.fontsAndColors,
      min: 8,
      max: 96,
      step: 1),
  PropertyMeta(
      key: 'fontFamily',
      minLevel: CapabilityLevel.basic,
      label: 'Font family',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'fontWeight',
      minLevel: CapabilityLevel.basic,
      label: 'Font weight',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'letterSpacing',
      minLevel: CapabilityLevel.advanced,
      label: 'Letter spacing',
      category: PropertyCategory.fontsAndColors,
      min: -2,
      max: 10,
      step: 0.5),
  PropertyMeta(
      key: 'borderWidth',
      minLevel: CapabilityLevel.advanced,
      label: 'Border width',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 20,
      step: 0.5),
  PropertyMeta(
      key: 'borderColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Border colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowBlur',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow blur',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 40,
      step: 1),
  PropertyMeta(
      key: 'shadowOffsetY',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow offset Y',
      category: PropertyCategory.layoutAndSpacing,
      min: -20,
      max: 20,
      step: 1),
  PropertyMeta(
      key: 'opacity',
      minLevel: CapabilityLevel.advanced,
      label: 'Opacity',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 1,
      step: 0.05),
  PropertyMeta(
      key: 'padding',
      minLevel: CapabilityLevel.basic,
      label: 'Padding',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 64,
      step: 1),
  PropertyMeta(
      key: 'width',
      minLevel: CapabilityLevel.basic,
      label: 'Width',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'height',
      minLevel: CapabilityLevel.basic,
      label: 'Height',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'visible',
      minLevel: CapabilityLevel.basic,
      label: 'Visible',
      safe: true,
      category: PropertyCategory.layoutAndSpacing),
];

const List<PropertyMeta> _tripstats = [
  PropertyMeta(
      key: 'label1',
      minLevel: CapabilityLevel.basic,
      label: 'Stat 1 label',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'value1',
      minLevel: CapabilityLevel.advanced,
      label: 'Stat 1 value',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'unit1',
      minLevel: CapabilityLevel.basic,
      label: 'Stat 1 unit',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'label2',
      minLevel: CapabilityLevel.basic,
      label: 'Stat 2 label',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'value2',
      minLevel: CapabilityLevel.advanced,
      label: 'Stat 2 value',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'unit2',
      minLevel: CapabilityLevel.basic,
      label: 'Stat 2 unit',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'label3',
      minLevel: CapabilityLevel.basic,
      label: 'Stat 3 label',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'value3',
      minLevel: CapabilityLevel.advanced,
      label: 'Stat 3 value',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'unit3',
      minLevel: CapabilityLevel.basic,
      label: 'Stat 3 unit',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'label4',
      minLevel: CapabilityLevel.basic,
      label: 'Stat 4 label',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'value4',
      minLevel: CapabilityLevel.advanced,
      label: 'Stat 4 value',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'unit4',
      minLevel: CapabilityLevel.basic,
      label: 'Stat 4 unit',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'layoutStyle',
      minLevel: CapabilityLevel.basic,
      label: 'Layout style',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'section1Header',
      minLevel: CapabilityLevel.basic,
      label: 'Section 1 Header',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'section1Val1',
      minLevel: CapabilityLevel.advanced,
      label: 'Section 1 Value 1',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'unit1_1',
      minLevel: CapabilityLevel.basic,
      label: 'Section 1 Unit 1',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'section1Val2',
      minLevel: CapabilityLevel.advanced,
      label: 'Section 1 Value 2',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'unit1_2',
      minLevel: CapabilityLevel.basic,
      label: 'Section 1 Unit 2',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'section1Val3',
      minLevel: CapabilityLevel.advanced,
      label: 'Section 1 Value 3',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'unit1_3',
      minLevel: CapabilityLevel.basic,
      label: 'Section 1 Unit 3',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'section2Header',
      minLevel: CapabilityLevel.basic,
      label: 'Section 2 Header',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'section2Val1',
      minLevel: CapabilityLevel.advanced,
      label: 'Section 2 Value 1',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'unit2_1',
      minLevel: CapabilityLevel.basic,
      label: 'Section 2 Unit 1',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'section2Val2',
      minLevel: CapabilityLevel.advanced,
      label: 'Section 2 Value 2',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'unit2_2',
      minLevel: CapabilityLevel.basic,
      label: 'Section 2 Unit 2',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'section2Val3',
      minLevel: CapabilityLevel.advanced,
      label: 'Section 2 Value 3',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'unit2_3',
      minLevel: CapabilityLevel.basic,
      label: 'Section 2 Unit 3',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'section3Header',
      minLevel: CapabilityLevel.basic,
      label: 'Section 3 Header',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'section3Val1',
      minLevel: CapabilityLevel.advanced,
      label: 'Section 3 Value 1',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'unit3_1',
      minLevel: CapabilityLevel.basic,
      label: 'Section 3 Unit 1',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'section3Val2',
      minLevel: CapabilityLevel.advanced,
      label: 'Section 3 Value 2',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'unit3_2',
      minLevel: CapabilityLevel.basic,
      label: 'Section 3 Unit 2',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'section3Val3',
      minLevel: CapabilityLevel.advanced,
      label: 'Section 3 Value 3',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'unit3_3',
      minLevel: CapabilityLevel.basic,
      label: 'Section 3 Unit 3',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'columns',
      minLevel: CapabilityLevel.basic,
      label: 'Columns',
      safe: true,
      category: PropertyCategory.visuals,
      min: 1,
      max: 6,
      step: 1),
  PropertyMeta(
      key: 'color',
      minLevel: CapabilityLevel.basic,
      label: 'Colour',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'accent',
      minLevel: CapabilityLevel.advanced,
      label: 'Accent colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'backgroundColor',
      minLevel: CapabilityLevel.basic,
      label: 'Background',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'borderRadius',
      minLevel: CapabilityLevel.advanced,
      label: 'Corner radius',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 48,
      step: 1),
  PropertyMeta(
      key: 'fontSize',
      minLevel: CapabilityLevel.basic,
      label: 'Font size',
      safe: true,
      category: PropertyCategory.fontsAndColors,
      min: 8,
      max: 96,
      step: 1),
  PropertyMeta(
      key: 'fontFamily',
      minLevel: CapabilityLevel.basic,
      label: 'Font family',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'fontWeight',
      minLevel: CapabilityLevel.basic,
      label: 'Font weight',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'letterSpacing',
      minLevel: CapabilityLevel.advanced,
      label: 'Letter spacing',
      category: PropertyCategory.fontsAndColors,
      min: -2,
      max: 10,
      step: 0.5),
  PropertyMeta(
      key: 'borderWidth',
      minLevel: CapabilityLevel.advanced,
      label: 'Border width',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 20,
      step: 0.5),
  PropertyMeta(
      key: 'borderColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Border colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowBlur',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow blur',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 40,
      step: 1),
  PropertyMeta(
      key: 'shadowOffsetY',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow offset Y',
      category: PropertyCategory.layoutAndSpacing,
      min: -20,
      max: 20,
      step: 1),
  PropertyMeta(
      key: 'opacity',
      minLevel: CapabilityLevel.advanced,
      label: 'Opacity',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 1,
      step: 0.05),
  PropertyMeta(
      key: 'padding',
      minLevel: CapabilityLevel.basic,
      label: 'Padding',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 64,
      step: 1),
  PropertyMeta(
      key: 'width',
      minLevel: CapabilityLevel.basic,
      label: 'Width',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'height',
      minLevel: CapabilityLevel.basic,
      label: 'Height',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'visible',
      minLevel: CapabilityLevel.basic,
      label: 'Visible',
      safe: true,
      category: PropertyCategory.layoutAndSpacing),
];

const List<PropertyMeta> _power = [
  PropertyMeta(
      key: 'power',
      minLevel: CapabilityLevel.advanced,
      label: 'Power binding',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'maxPower',
      minLevel: CapabilityLevel.basic,
      label: 'Max power',
      safe: true,
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'regen',
      minLevel: CapabilityLevel.advanced,
      label: 'Regen binding',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'maxRegen',
      minLevel: CapabilityLevel.basic,
      label: 'Max regen',
      safe: true,
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'color',
      minLevel: CapabilityLevel.basic,
      label: 'Power colour',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'regenColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Regen colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'accent',
      minLevel: CapabilityLevel.advanced,
      label: 'Accent colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'showBars',
      minLevel: CapabilityLevel.basic,
      label: 'Show bars',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'label',
      minLevel: CapabilityLevel.basic,
      label: 'Label',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'backgroundColor',
      minLevel: CapabilityLevel.basic,
      label: 'Background',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'borderRadius',
      minLevel: CapabilityLevel.advanced,
      label: 'Corner radius',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 48,
      step: 1),
  PropertyMeta(
      key: 'fontSize',
      minLevel: CapabilityLevel.basic,
      label: 'Font size',
      safe: true,
      category: PropertyCategory.fontsAndColors,
      min: 8,
      max: 96,
      step: 1),
  PropertyMeta(
      key: 'fontFamily',
      minLevel: CapabilityLevel.basic,
      label: 'Font family',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'fontWeight',
      minLevel: CapabilityLevel.basic,
      label: 'Font weight',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'letterSpacing',
      minLevel: CapabilityLevel.advanced,
      label: 'Letter spacing',
      category: PropertyCategory.fontsAndColors,
      min: -2,
      max: 10,
      step: 0.5),
  PropertyMeta(
      key: 'borderWidth',
      minLevel: CapabilityLevel.advanced,
      label: 'Border width',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 20,
      step: 0.5),
  PropertyMeta(
      key: 'borderColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Border colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowBlur',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow blur',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 40,
      step: 1),
  PropertyMeta(
      key: 'shadowOffsetY',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow offset Y',
      category: PropertyCategory.layoutAndSpacing,
      min: -20,
      max: 20,
      step: 1),
  PropertyMeta(
      key: 'opacity',
      minLevel: CapabilityLevel.advanced,
      label: 'Opacity',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 1,
      step: 0.05),
  PropertyMeta(
      key: 'padding',
      minLevel: CapabilityLevel.basic,
      label: 'Padding',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 64,
      step: 1),
  PropertyMeta(
      key: 'width',
      minLevel: CapabilityLevel.basic,
      label: 'Width',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'height',
      minLevel: CapabilityLevel.basic,
      label: 'Height',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'visible',
      minLevel: CapabilityLevel.basic,
      label: 'Visible',
      safe: true,
      category: PropertyCategory.layoutAndSpacing),
];

const List<PropertyMeta> _warnings = [
  PropertyMeta(
      key: 'activeWarnings',
      minLevel: CapabilityLevel.advanced,
      label: 'Active warnings',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'color',
      minLevel: CapabilityLevel.basic,
      label: 'Error colour',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'warningColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Warning colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'infoColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Info colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'iconSize',
      minLevel: CapabilityLevel.basic,
      label: 'Icon size',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'backgroundColor',
      minLevel: CapabilityLevel.basic,
      label: 'Background',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'borderRadius',
      minLevel: CapabilityLevel.advanced,
      label: 'Corner radius',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 48,
      step: 1),
  PropertyMeta(
      key: 'borderWidth',
      minLevel: CapabilityLevel.advanced,
      label: 'Border width',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 20,
      step: 0.5),
  PropertyMeta(
      key: 'borderColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Border colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowBlur',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow blur',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 40,
      step: 1),
  PropertyMeta(
      key: 'shadowOffsetY',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow offset Y',
      category: PropertyCategory.layoutAndSpacing,
      min: -20,
      max: 20,
      step: 1),
  PropertyMeta(
      key: 'opacity',
      minLevel: CapabilityLevel.advanced,
      label: 'Opacity',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 1,
      step: 0.05),
  PropertyMeta(
      key: 'padding',
      minLevel: CapabilityLevel.basic,
      label: 'Padding',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 64,
      step: 1),
  PropertyMeta(
      key: 'width',
      minLevel: CapabilityLevel.basic,
      label: 'Width',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'height',
      minLevel: CapabilityLevel.basic,
      label: 'Height',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'visible',
      minLevel: CapabilityLevel.basic,
      label: 'Visible',
      safe: true,
      category: PropertyCategory.layoutAndSpacing),
];

const List<PropertyMeta> _minigauge = [
  PropertyMeta(
      key: 'value',
      minLevel: CapabilityLevel.advanced,
      label: 'Value binding',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'min',
      minLevel: CapabilityLevel.basic,
      label: 'Minimum',
      safe: true,
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'max',
      minLevel: CapabilityLevel.basic,
      label: 'Maximum',
      safe: true,
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'label',
      minLevel: CapabilityLevel.basic,
      label: 'Label',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'unit',
      minLevel: CapabilityLevel.basic,
      label: 'Unit',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'sourceUnit',
      minLevel: CapabilityLevel.advanced,
      label: 'Source temp. unit (celsius/fahrenheit/kelvin)',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'displayUnit',
      minLevel: CapabilityLevel.basic,
      label: 'Display temp. unit (celsius/fahrenheit/kelvin)',
      safe: true,
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'icon',
      minLevel: CapabilityLevel.basic,
      label: 'Icon',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'style',
      minLevel: CapabilityLevel.basic,
      label: 'Style',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'orientation',
      minLevel: CapabilityLevel.advanced,
      label: 'Orientation',
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'color',
      minLevel: CapabilityLevel.basic,
      label: 'Colour',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'accent',
      minLevel: CapabilityLevel.advanced,
      label: 'Accent colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'backgroundColor',
      minLevel: CapabilityLevel.basic,
      label: 'Background',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'borderRadius',
      minLevel: CapabilityLevel.advanced,
      label: 'Corner radius',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 48,
      step: 1),
  PropertyMeta(
      key: 'fontSize',
      minLevel: CapabilityLevel.basic,
      label: 'Font size',
      safe: true,
      category: PropertyCategory.fontsAndColors,
      min: 8,
      max: 96,
      step: 1),
  PropertyMeta(
      key: 'fontFamily',
      minLevel: CapabilityLevel.basic,
      label: 'Font family',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'fontWeight',
      minLevel: CapabilityLevel.basic,
      label: 'Font weight',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'letterSpacing',
      minLevel: CapabilityLevel.advanced,
      label: 'Letter spacing',
      category: PropertyCategory.fontsAndColors,
      min: -2,
      max: 10,
      step: 0.5),
  PropertyMeta(
      key: 'borderWidth',
      minLevel: CapabilityLevel.advanced,
      label: 'Border width',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 20,
      step: 0.5),
  PropertyMeta(
      key: 'borderColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Border colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowBlur',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow blur',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 40,
      step: 1),
  PropertyMeta(
      key: 'shadowOffsetY',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow offset Y',
      category: PropertyCategory.layoutAndSpacing,
      min: -20,
      max: 20,
      step: 1),
  PropertyMeta(
      key: 'opacity',
      minLevel: CapabilityLevel.advanced,
      label: 'Opacity',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 1,
      step: 0.05),
  PropertyMeta(
      key: 'padding',
      minLevel: CapabilityLevel.basic,
      label: 'Padding',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 64,
      step: 1),
  PropertyMeta(
      key: 'width',
      minLevel: CapabilityLevel.basic,
      label: 'Width',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'height',
      minLevel: CapabilityLevel.basic,
      label: 'Height',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'visible',
      minLevel: CapabilityLevel.basic,
      label: 'Visible',
      safe: true,
      category: PropertyCategory.layoutAndSpacing),
];

const List<PropertyMeta> _appgrid = [
  PropertyMeta(
      key: 'apps',
      minLevel: CapabilityLevel.basic,
      label: 'Apps list',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'columns',
      minLevel: CapabilityLevel.basic,
      label: 'Columns',
      safe: true,
      category: PropertyCategory.visuals,
      min: 1,
      max: 6,
      step: 1),
  PropertyMeta(
      key: 'iconSize',
      minLevel: CapabilityLevel.basic,
      label: 'Icon size',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'showLabels',
      minLevel: CapabilityLevel.basic,
      label: 'Show labels',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'color',
      minLevel: CapabilityLevel.basic,
      label: 'Colour',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'accent',
      minLevel: CapabilityLevel.advanced,
      label: 'Accent colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'backgroundColor',
      minLevel: CapabilityLevel.basic,
      label: 'Background',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'borderRadius',
      minLevel: CapabilityLevel.advanced,
      label: 'Corner radius',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 48,
      step: 1),
  PropertyMeta(
      key: 'fontSize',
      minLevel: CapabilityLevel.basic,
      label: 'Font size',
      safe: true,
      category: PropertyCategory.fontsAndColors,
      min: 8,
      max: 96,
      step: 1),
  PropertyMeta(
      key: 'borderWidth',
      minLevel: CapabilityLevel.advanced,
      label: 'Border width',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 20,
      step: 0.5),
  PropertyMeta(
      key: 'borderColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Border colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowBlur',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow blur',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 40,
      step: 1),
  PropertyMeta(
      key: 'shadowOffsetY',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow offset Y',
      category: PropertyCategory.layoutAndSpacing,
      min: -20,
      max: 20,
      step: 1),
  PropertyMeta(
      key: 'opacity',
      minLevel: CapabilityLevel.advanced,
      label: 'Opacity',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 1,
      step: 0.05),
  PropertyMeta(
      key: 'padding',
      minLevel: CapabilityLevel.basic,
      label: 'Padding',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 64,
      step: 1),
  PropertyMeta(
      key: 'width',
      minLevel: CapabilityLevel.basic,
      label: 'Width',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'height',
      minLevel: CapabilityLevel.basic,
      label: 'Height',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'visible',
      minLevel: CapabilityLevel.basic,
      label: 'Visible',
      safe: true,
      category: PropertyCategory.layoutAndSpacing),
];

const List<PropertyMeta> _statusbar = [
  PropertyMeta(
      key: 'time',
      minLevel: CapabilityLevel.basic,
      label: 'Time',
      safe: true,
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'battery',
      minLevel: CapabilityLevel.advanced,
      label: 'Battery level',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'signal',
      minLevel: CapabilityLevel.advanced,
      label: 'Signal level',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'showTime',
      minLevel: CapabilityLevel.basic,
      label: 'Show time',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'showBattery',
      minLevel: CapabilityLevel.basic,
      label: 'Show battery',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'showSignal',
      minLevel: CapabilityLevel.basic,
      label: 'Show signal',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'color',
      minLevel: CapabilityLevel.basic,
      label: 'Colour',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'accent',
      minLevel: CapabilityLevel.advanced,
      label: 'Accent colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'backgroundColor',
      minLevel: CapabilityLevel.basic,
      label: 'Background',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'borderRadius',
      minLevel: CapabilityLevel.advanced,
      label: 'Corner radius',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 48,
      step: 1),
  PropertyMeta(
      key: 'fontSize',
      minLevel: CapabilityLevel.basic,
      label: 'Font size',
      safe: true,
      category: PropertyCategory.fontsAndColors,
      min: 8,
      max: 96,
      step: 1),
  PropertyMeta(
      key: 'fontFamily',
      minLevel: CapabilityLevel.basic,
      label: 'Font family',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'fontWeight',
      minLevel: CapabilityLevel.basic,
      label: 'Font weight',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'letterSpacing',
      minLevel: CapabilityLevel.advanced,
      label: 'Letter spacing',
      category: PropertyCategory.fontsAndColors,
      min: -2,
      max: 10,
      step: 0.5),
  PropertyMeta(
      key: 'borderWidth',
      minLevel: CapabilityLevel.advanced,
      label: 'Border width',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 20,
      step: 0.5),
  PropertyMeta(
      key: 'borderColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Border colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowBlur',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow blur',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 40,
      step: 1),
  PropertyMeta(
      key: 'shadowOffsetY',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow offset Y',
      category: PropertyCategory.layoutAndSpacing,
      min: -20,
      max: 20,
      step: 1),
  PropertyMeta(
      key: 'opacity',
      minLevel: CapabilityLevel.advanced,
      label: 'Opacity',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 1,
      step: 0.05),
  PropertyMeta(
      key: 'padding',
      minLevel: CapabilityLevel.basic,
      label: 'Padding',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 64,
      step: 1),
  PropertyMeta(
      key: 'width',
      minLevel: CapabilityLevel.basic,
      label: 'Width',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'height',
      minLevel: CapabilityLevel.basic,
      label: 'Height',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'visible',
      minLevel: CapabilityLevel.basic,
      label: 'Visible',
      safe: true,
      category: PropertyCategory.layoutAndSpacing),
];

const List<PropertyMeta> _climate = [
  PropertyMeta(
      key: 'temperature',
      minLevel: CapabilityLevel.advanced,
      label: 'Temperature',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'targetTemp',
      minLevel: CapabilityLevel.advanced,
      label: 'Target temperature',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'fanSpeed',
      minLevel: CapabilityLevel.advanced,
      label: 'Fan speed',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'mode',
      minLevel: CapabilityLevel.basic,
      label: 'Mode',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'unit',
      minLevel: CapabilityLevel.basic,
      label: 'Unit',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'color',
      minLevel: CapabilityLevel.basic,
      label: 'Colour',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'accent',
      minLevel: CapabilityLevel.advanced,
      label: 'Accent colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'backgroundColor',
      minLevel: CapabilityLevel.basic,
      label: 'Background',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'borderRadius',
      minLevel: CapabilityLevel.advanced,
      label: 'Corner radius',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 48,
      step: 1),
  PropertyMeta(
      key: 'fontSize',
      minLevel: CapabilityLevel.basic,
      label: 'Font size',
      safe: true,
      category: PropertyCategory.fontsAndColors,
      min: 8,
      max: 96,
      step: 1),
  PropertyMeta(
      key: 'fontFamily',
      minLevel: CapabilityLevel.basic,
      label: 'Font family',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'fontWeight',
      minLevel: CapabilityLevel.basic,
      label: 'Font weight',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'letterSpacing',
      minLevel: CapabilityLevel.advanced,
      label: 'Letter spacing',
      category: PropertyCategory.fontsAndColors,
      min: -2,
      max: 10,
      step: 0.5),
  PropertyMeta(
      key: 'borderWidth',
      minLevel: CapabilityLevel.advanced,
      label: 'Border width',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 20,
      step: 0.5),
  PropertyMeta(
      key: 'borderColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Border colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowBlur',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow blur',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 40,
      step: 1),
  PropertyMeta(
      key: 'shadowOffsetY',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow offset Y',
      category: PropertyCategory.layoutAndSpacing,
      min: -20,
      max: 20,
      step: 1),
  PropertyMeta(
      key: 'opacity',
      minLevel: CapabilityLevel.advanced,
      label: 'Opacity',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 1,
      step: 0.05),
  PropertyMeta(
      key: 'padding',
      minLevel: CapabilityLevel.basic,
      label: 'Padding',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 64,
      step: 1),
  PropertyMeta(
      key: 'width',
      minLevel: CapabilityLevel.basic,
      label: 'Width',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'height',
      minLevel: CapabilityLevel.basic,
      label: 'Height',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'visible',
      minLevel: CapabilityLevel.basic,
      label: 'Visible',
      safe: true,
      category: PropertyCategory.layoutAndSpacing),
];

const List<PropertyMeta> _car_viz = [
  PropertyMeta(
      key: 'laneLeft',
      minLevel: CapabilityLevel.advanced,
      label: 'Left lane warning',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'laneRight',
      minLevel: CapabilityLevel.advanced,
      label: 'Right lane warning',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'carAhead',
      minLevel: CapabilityLevel.advanced,
      label: 'Car ahead',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'doorLeft',
      minLevel: CapabilityLevel.basic,
      label: 'Left door open',
      safe: true,
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'doorRight',
      minLevel: CapabilityLevel.basic,
      label: 'Right door open',
      safe: true,
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'showRing',
      minLevel: CapabilityLevel.basic,
      label: 'Show Pod Ring',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'showLabels',
      minLevel: CapabilityLevel.basic,
      label: 'Show Pod Labels',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'label',
      minLevel: CapabilityLevel.basic,
      label: 'Label',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'color',
      minLevel: CapabilityLevel.basic,
      label: 'Colour',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'accent',
      minLevel: CapabilityLevel.advanced,
      label: 'Accent colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'backgroundColor',
      minLevel: CapabilityLevel.basic,
      label: 'Background',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'fontSize',
      minLevel: CapabilityLevel.basic,
      label: 'Font size',
      safe: true,
      category: PropertyCategory.fontsAndColors,
      min: 8,
      max: 96,
      step: 1),
  PropertyMeta(
      key: 'fontFamily',
      minLevel: CapabilityLevel.basic,
      label: 'Font family',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'fontWeight',
      minLevel: CapabilityLevel.basic,
      label: 'Font weight',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'letterSpacing',
      minLevel: CapabilityLevel.advanced,
      label: 'Letter spacing',
      category: PropertyCategory.fontsAndColors,
      min: -2,
      max: 10,
      step: 0.5),
  PropertyMeta(
      key: 'borderRadius',
      minLevel: CapabilityLevel.advanced,
      label: 'Corner radius',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 48,
      step: 1),
  PropertyMeta(
      key: 'borderWidth',
      minLevel: CapabilityLevel.advanced,
      label: 'Border width',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 20,
      step: 0.5),
  PropertyMeta(
      key: 'borderColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Border colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowBlur',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow blur',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 40,
      step: 1),
  PropertyMeta(
      key: 'shadowOffsetY',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow offset Y',
      category: PropertyCategory.layoutAndSpacing,
      min: -20,
      max: 20,
      step: 1),
  PropertyMeta(
      key: 'opacity',
      minLevel: CapabilityLevel.advanced,
      label: 'Opacity',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 1,
      step: 0.05),
  PropertyMeta(
      key: 'padding',
      minLevel: CapabilityLevel.basic,
      label: 'Padding',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 64,
      step: 1),
  PropertyMeta(
      key: 'width',
      minLevel: CapabilityLevel.basic,
      label: 'Width',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'height',
      minLevel: CapabilityLevel.basic,
      label: 'Height',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'visible',
      minLevel: CapabilityLevel.basic,
      label: 'Visible',
      safe: true,
      category: PropertyCategory.layoutAndSpacing),
];

const List<PropertyMeta> _map = [
  PropertyMeta(
      key: 'label',
      minLevel: CapabilityLevel.basic,
      label: 'Label',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'eta',
      minLevel: CapabilityLevel.advanced,
      label: 'ETA',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'distance',
      minLevel: CapabilityLevel.advanced,
      label: 'Distance',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'nextTurn',
      minLevel: CapabilityLevel.advanced,
      label: 'Next turn',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'showMapGraphic',
      minLevel: CapabilityLevel.basic,
      label: 'Show map graphic',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'mapStyle',
      minLevel: CapabilityLevel.basic,
      label: 'Map style',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'color',
      minLevel: CapabilityLevel.basic,
      label: 'Colour',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'accent',
      minLevel: CapabilityLevel.advanced,
      label: 'Accent colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'backgroundColor',
      minLevel: CapabilityLevel.basic,
      label: 'Background',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'borderRadius',
      minLevel: CapabilityLevel.advanced,
      label: 'Corner radius',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 48,
      step: 1),
  PropertyMeta(
      key: 'borderWidth',
      minLevel: CapabilityLevel.advanced,
      label: 'Border width',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 20,
      step: 0.5),
  PropertyMeta(
      key: 'borderColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Border colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowBlur',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow blur',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 40,
      step: 1),
  PropertyMeta(
      key: 'shadowOffsetY',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow offset Y',
      category: PropertyCategory.layoutAndSpacing,
      min: -20,
      max: 20,
      step: 1),
  PropertyMeta(
      key: 'opacity',
      minLevel: CapabilityLevel.advanced,
      label: 'Opacity',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 1,
      step: 0.05),
  PropertyMeta(
      key: 'padding',
      minLevel: CapabilityLevel.basic,
      label: 'Padding',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 64,
      step: 1),
  PropertyMeta(
      key: 'width',
      minLevel: CapabilityLevel.basic,
      label: 'Width',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'height',
      minLevel: CapabilityLevel.basic,
      label: 'Height',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'visible',
      minLevel: CapabilityLevel.basic,
      label: 'Visible',
      safe: true,
      category: PropertyCategory.layoutAndSpacing),
];

const List<PropertyMeta> _gear_selector = [
  PropertyMeta(
      key: 'currentGear',
      minLevel: CapabilityLevel.basic,
      label: 'Current gear',
      safe: true,
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'gears',
      minLevel: CapabilityLevel.basic,
      label: 'Gear list',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'color',
      minLevel: CapabilityLevel.basic,
      label: 'Colour',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'activeColor',
      minLevel: CapabilityLevel.basic,
      label: 'Active colour',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'inactiveColor',
      minLevel: CapabilityLevel.basic,
      label: 'Inactive colour',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'backgroundColor',
      minLevel: CapabilityLevel.basic,
      label: 'Background',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'borderRadius',
      minLevel: CapabilityLevel.advanced,
      label: 'Corner radius',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 48,
      step: 1),
  PropertyMeta(
      key: 'fontSize',
      minLevel: CapabilityLevel.basic,
      label: 'Font size',
      safe: true,
      category: PropertyCategory.fontsAndColors,
      min: 8,
      max: 96,
      step: 1),
  PropertyMeta(
      key: 'fontFamily',
      minLevel: CapabilityLevel.basic,
      label: 'Font family',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'fontWeight',
      minLevel: CapabilityLevel.basic,
      label: 'Font weight',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'letterSpacing',
      minLevel: CapabilityLevel.advanced,
      label: 'Letter spacing',
      category: PropertyCategory.fontsAndColors,
      min: -2,
      max: 10,
      step: 0.5),
  PropertyMeta(
      key: 'borderWidth',
      minLevel: CapabilityLevel.advanced,
      label: 'Border width',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 20,
      step: 0.5),
  PropertyMeta(
      key: 'borderColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Border colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowBlur',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow blur',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 40,
      step: 1),
  PropertyMeta(
      key: 'shadowOffsetY',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow offset Y',
      category: PropertyCategory.layoutAndSpacing,
      min: -20,
      max: 20,
      step: 1),
  PropertyMeta(
      key: 'opacity',
      minLevel: CapabilityLevel.advanced,
      label: 'Opacity',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 1,
      step: 0.05),
  PropertyMeta(
      key: 'padding',
      minLevel: CapabilityLevel.basic,
      label: 'Padding',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 64,
      step: 1),
  PropertyMeta(
      key: 'width',
      minLevel: CapabilityLevel.basic,
      label: 'Width',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'height',
      minLevel: CapabilityLevel.basic,
      label: 'Height',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'visible',
      minLevel: CapabilityLevel.basic,
      label: 'Visible',
      safe: true,
      category: PropertyCategory.layoutAndSpacing),
];

const List<PropertyMeta> _battery_range = [
  PropertyMeta(
      key: 'batteryLevel',
      minLevel: CapabilityLevel.advanced,
      label: 'Battery level (0-1)',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'range',
      minLevel: CapabilityLevel.advanced,
      label: 'Range',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'temperature',
      minLevel: CapabilityLevel.advanced,
      label: 'Temperature',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'color',
      minLevel: CapabilityLevel.basic,
      label: 'Bar colour',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'textColor',
      minLevel: CapabilityLevel.basic,
      label: 'Text colour',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'accentColor',
      minLevel: CapabilityLevel.basic,
      label: 'Accent colour',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'showRange',
      minLevel: CapabilityLevel.basic,
      label: 'Show range',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'showTemperature',
      minLevel: CapabilityLevel.basic,
      label: 'Show temperature',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'unit',
      minLevel: CapabilityLevel.basic,
      label: 'Range unit',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'tempUnit',
      minLevel: CapabilityLevel.basic,
      label: 'Temp unit',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'backgroundColor',
      minLevel: CapabilityLevel.basic,
      label: 'Background',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'borderRadius',
      minLevel: CapabilityLevel.advanced,
      label: 'Corner radius',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 48,
      step: 1),
  PropertyMeta(
      key: 'fontSize',
      minLevel: CapabilityLevel.basic,
      label: 'Font size',
      safe: true,
      category: PropertyCategory.fontsAndColors,
      min: 8,
      max: 96,
      step: 1),
  PropertyMeta(
      key: 'fontFamily',
      minLevel: CapabilityLevel.basic,
      label: 'Font family',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'fontWeight',
      minLevel: CapabilityLevel.basic,
      label: 'Font weight',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'letterSpacing',
      minLevel: CapabilityLevel.advanced,
      label: 'Letter spacing',
      category: PropertyCategory.fontsAndColors,
      min: -2,
      max: 10,
      step: 0.5),
  PropertyMeta(
      key: 'borderWidth',
      minLevel: CapabilityLevel.advanced,
      label: 'Border width',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 20,
      step: 0.5),
  PropertyMeta(
      key: 'borderColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Border colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowBlur',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow blur',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 40,
      step: 1),
  PropertyMeta(
      key: 'shadowOffsetY',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow offset Y',
      category: PropertyCategory.layoutAndSpacing,
      min: -20,
      max: 20,
      step: 1),
  PropertyMeta(
      key: 'opacity',
      minLevel: CapabilityLevel.advanced,
      label: 'Opacity',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 1,
      step: 0.05),
  PropertyMeta(
      key: 'padding',
      minLevel: CapabilityLevel.basic,
      label: 'Padding',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 64,
      step: 1),
  PropertyMeta(
      key: 'width',
      minLevel: CapabilityLevel.basic,
      label: 'Width',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'height',
      minLevel: CapabilityLevel.basic,
      label: 'Height',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'visible',
      minLevel: CapabilityLevel.basic,
      label: 'Visible',
      safe: true,
      category: PropertyCategory.layoutAndSpacing),
];

const List<PropertyMeta> _power_flow = [
  PropertyMeta(
      key: 'power',
      minLevel: CapabilityLevel.advanced,
      label: 'Power',
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'maxPower',
      minLevel: CapabilityLevel.basic,
      label: 'Max power',
      safe: true,
      category: PropertyCategory.dataBindings),
  PropertyMeta(
      key: 'color',
      minLevel: CapabilityLevel.basic,
      label: 'Bar colour',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'accent',
      minLevel: CapabilityLevel.basic,
      label: 'Accent colour',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'label',
      minLevel: CapabilityLevel.basic,
      label: 'Label',
      safe: true,
      category: PropertyCategory.visuals),
  PropertyMeta(
      key: 'barWidth',
      minLevel: CapabilityLevel.advanced,
      label: 'Bar width',
      category: PropertyCategory.visuals,
      min: 1,
      max: 100,
      step: 1),
  PropertyMeta(
      key: 'barHeight',
      minLevel: CapabilityLevel.advanced,
      label: 'Bar height',
      category: PropertyCategory.visuals,
      min: 1,
      max: 500,
      step: 1),
  PropertyMeta(
      key: 'backgroundColor',
      minLevel: CapabilityLevel.basic,
      label: 'Background',
      safe: true,
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'borderRadius',
      minLevel: CapabilityLevel.advanced,
      label: 'Corner radius',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 48,
      step: 1),
  PropertyMeta(
      key: 'fontSize',
      minLevel: CapabilityLevel.basic,
      label: 'Font size',
      safe: true,
      category: PropertyCategory.fontsAndColors,
      min: 8,
      max: 96,
      step: 1),
  PropertyMeta(
      key: 'borderWidth',
      minLevel: CapabilityLevel.advanced,
      label: 'Border width',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 20,
      step: 0.5),
  PropertyMeta(
      key: 'borderColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Border colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowColor',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow colour',
      category: PropertyCategory.fontsAndColors),
  PropertyMeta(
      key: 'shadowBlur',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow blur',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 40,
      step: 1),
  PropertyMeta(
      key: 'shadowOffsetY',
      minLevel: CapabilityLevel.advanced,
      label: 'Shadow offset Y',
      category: PropertyCategory.layoutAndSpacing,
      min: -20,
      max: 20,
      step: 1),
  PropertyMeta(
      key: 'opacity',
      minLevel: CapabilityLevel.advanced,
      label: 'Opacity',
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 1,
      step: 0.05),
  PropertyMeta(
      key: 'padding',
      minLevel: CapabilityLevel.basic,
      label: 'Padding',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 0,
      max: 64,
      step: 1),
  PropertyMeta(
      key: 'width',
      minLevel: CapabilityLevel.basic,
      label: 'Width',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'height',
      minLevel: CapabilityLevel.basic,
      label: 'Height',
      safe: true,
      category: PropertyCategory.layoutAndSpacing,
      min: 50,
      max: 800,
      step: 10),
  PropertyMeta(
      key: 'visible',
      minLevel: CapabilityLevel.basic,
      label: 'Visible',
      safe: true,
      category: PropertyCategory.layoutAndSpacing),
];

const Map<String, List<PropertyMeta>> propertyManifest = {
  'gauge': _gauge,
  'bar': _bar,
  'text': _text,
  'status': _status,
  'chart': _chart,
  'image': _image,
  'web': _web,
  'paint': _paint,
  'digitalspeed': _digitalspeed,
  'music': _music,
  'tripstats': _tripstats,
  'power': _power,
  'warnings': _warnings,
  'minigauge': _minigauge,
  'appgrid': _appgrid,
  'statusbar': _statusbar,
  'climate': _climate,
  'car_viz': _car_viz,
  'map': _map,
  'gear_selector': _gear_selector,
  'battery_range': _battery_range,
  'power_flow': _power_flow,
};

List<PropertyMeta> visibleProperties(String widgetKind, CapabilityLevel level) {
  final manifest = propertyManifest[widgetKind] ?? const <PropertyMeta>[];
  return manifest.where((m) => level.includes(m.minLevel)).toList();
}

List<PropertyMeta> allProperties(String widgetKind) {
  return (propertyManifest[widgetKind] ?? const <PropertyMeta>[]).toList();
}

Map<PropertyCategory, List<PropertyMeta>> _groupPropertiesByCategory(
  String widgetKind, {
  CapabilityLevel? level,
}) {
  final props = level != null
      ? visibleProperties(widgetKind, level)
      : allProperties(widgetKind);
  final map = <PropertyCategory, List<PropertyMeta>>{
    for (final cat in PropertyCategory.values) cat: [],
  };
  for (final meta in props) {
    map[meta.category]?.add(meta);
  }
  return map;
}

Map<PropertyCategory, List<PropertyMeta>> categorizedProperties(
  String widgetKind, {
  CapabilityLevel? level,
}) =>
    _groupPropertiesByCategory(widgetKind, level: level);

Map<PropertyCategory, List<PropertyMeta>> propertiesByCategory(
  String widgetKind, {
  CapabilityLevel? level,
}) =>
    _groupPropertiesByCategory(widgetKind, level: level);

List<PropertyMeta> getPropertiesByCategory(
  String widgetKind,
  PropertyCategory category, {
  CapabilityLevel? level,
}) {
  return (_groupPropertiesByCategory(widgetKind, level: level)[category] ??
      const <PropertyMeta>[]);
}

bool transformsUnlockedAt(CapabilityLevel level) =>
    level.index >= CapabilityLevel.advanced.index;
