/// Per-property capability-level metadata for the inspector.
///
/// The studio inspector consults this to decide which properties to reveal at
/// the user's chosen level. Basic mode shows only "safe" knobs (colour, label,
/// limits); Advanced adds layout/bindings; Expert exposes everything including
/// raw transform values and graph bindings.
library;

import 'package:dashboard_model/dashboard_model.dart';

/// Metadata for a single widget property.
class PropertyMeta {
  final String key;
  final CapabilityLevel minLevel;
  final String label;
  final bool safe;

  const PropertyMeta({
    required this.key,
    required this.minLevel,
    required this.label,
    this.safe = false,
  });
}

const List<PropertyMeta> _gauge = [
  PropertyMeta(key: 'value', minLevel: CapabilityLevel.advanced, label: 'Value binding'),
  PropertyMeta(key: 'min', minLevel: CapabilityLevel.basic, label: 'Minimum', safe: true),
  PropertyMeta(key: 'max', minLevel: CapabilityLevel.basic, label: 'Maximum', safe: true),
  PropertyMeta(key: 'label', minLevel: CapabilityLevel.basic, label: 'Label', safe: true),
  PropertyMeta(key: 'unit', minLevel: CapabilityLevel.basic, label: 'Unit', safe: true),
  PropertyMeta(key: 'color', minLevel: CapabilityLevel.basic, label: 'Colour', safe: true),
  PropertyMeta(key: 'accent', minLevel: CapabilityLevel.advanced, label: 'Accent colour'),
  PropertyMeta(key: 'tickCount', minLevel: CapabilityLevel.advanced, label: 'Tick count'),
  PropertyMeta(key: 'sweepAngle', minLevel: CapabilityLevel.advanced, label: 'Sweep angle (°)'),
  PropertyMeta(key: 'startAngle', minLevel: CapabilityLevel.advanced, label: 'Start angle (°)'),
  PropertyMeta(key: 'arcWidth', minLevel: CapabilityLevel.advanced, label: 'Arc thickness'),
  PropertyMeta(key: 'needleStyle', minLevel: CapabilityLevel.advanced, label: 'Needle style'),
  PropertyMeta(key: 'backgroundColor', minLevel: CapabilityLevel.basic, label: 'Background', safe: true),
  PropertyMeta(key: 'borderRadius', minLevel: CapabilityLevel.advanced, label: 'Corner radius'),
  PropertyMeta(key: 'fontSize', minLevel: CapabilityLevel.basic, label: 'Font size', safe: true),
  PropertyMeta(key: 'borderWidth', minLevel: CapabilityLevel.advanced, label: 'Border width'),
  PropertyMeta(key: 'borderColor', minLevel: CapabilityLevel.advanced, label: 'Border colour'),
  PropertyMeta(key: 'shadowColor', minLevel: CapabilityLevel.advanced, label: 'Shadow colour'),
  PropertyMeta(key: 'shadowBlur', minLevel: CapabilityLevel.advanced, label: 'Shadow blur'),
  PropertyMeta(key: 'shadowOffsetY', minLevel: CapabilityLevel.advanced, label: 'Shadow offset Y'),
  PropertyMeta(key: 'opacity', minLevel: CapabilityLevel.advanced, label: 'Opacity'),
  PropertyMeta(key: 'padding', minLevel: CapabilityLevel.basic, label: 'Padding', safe: true),
  PropertyMeta(key: 'width', minLevel: CapabilityLevel.basic, label: 'Width', safe: true),
  PropertyMeta(key: 'height', minLevel: CapabilityLevel.basic, label: 'Height', safe: true),
  PropertyMeta(key: 'visible', minLevel: CapabilityLevel.basic, label: 'Visible', safe: true),
];

const List<PropertyMeta> _bar = [
  PropertyMeta(key: 'value', minLevel: CapabilityLevel.advanced, label: 'Value binding'),
  PropertyMeta(key: 'min', minLevel: CapabilityLevel.basic, label: 'Minimum', safe: true),
  PropertyMeta(key: 'max', minLevel: CapabilityLevel.basic, label: 'Maximum', safe: true),
  PropertyMeta(key: 'color', minLevel: CapabilityLevel.basic, label: 'Colour', safe: true),
  PropertyMeta(key: 'orientation', minLevel: CapabilityLevel.advanced, label: 'Orientation'),
  PropertyMeta(key: 'backgroundColor', minLevel: CapabilityLevel.basic, label: 'Background', safe: true),
  PropertyMeta(key: 'borderRadius', minLevel: CapabilityLevel.advanced, label: 'Corner radius'),
  PropertyMeta(key: 'fontSize', minLevel: CapabilityLevel.basic, label: 'Font size', safe: true),
  PropertyMeta(key: 'borderWidth', minLevel: CapabilityLevel.advanced, label: 'Border width'),
  PropertyMeta(key: 'borderColor', minLevel: CapabilityLevel.advanced, label: 'Border colour'),
  PropertyMeta(key: 'shadowColor', minLevel: CapabilityLevel.advanced, label: 'Shadow colour'),
  PropertyMeta(key: 'shadowBlur', minLevel: CapabilityLevel.advanced, label: 'Shadow blur'),
  PropertyMeta(key: 'shadowOffsetY', minLevel: CapabilityLevel.advanced, label: 'Shadow offset Y'),
  PropertyMeta(key: 'opacity', minLevel: CapabilityLevel.advanced, label: 'Opacity'),
  PropertyMeta(key: 'padding', minLevel: CapabilityLevel.basic, label: 'Padding', safe: true),
  PropertyMeta(key: 'width', minLevel: CapabilityLevel.basic, label: 'Width', safe: true),
  PropertyMeta(key: 'height', minLevel: CapabilityLevel.basic, label: 'Height', safe: true),
  PropertyMeta(key: 'visible', minLevel: CapabilityLevel.basic, label: 'Visible', safe: true),
];

const List<PropertyMeta> _text = [
  PropertyMeta(key: 'value', minLevel: CapabilityLevel.advanced, label: 'Value binding'),
  PropertyMeta(key: 'label', minLevel: CapabilityLevel.basic, label: 'Label', safe: true),
  PropertyMeta(key: 'unit', minLevel: CapabilityLevel.basic, label: 'Unit', safe: true),
  PropertyMeta(key: 'color', minLevel: CapabilityLevel.basic, label: 'Colour', safe: true),
  PropertyMeta(key: 'backgroundColor', minLevel: CapabilityLevel.basic, label: 'Background', safe: true),
  PropertyMeta(key: 'borderRadius', minLevel: CapabilityLevel.advanced, label: 'Corner radius'),
  PropertyMeta(key: 'fontSize', minLevel: CapabilityLevel.basic, label: 'Font size', safe: true),
  PropertyMeta(key: 'borderWidth', minLevel: CapabilityLevel.advanced, label: 'Border width'),
  PropertyMeta(key: 'borderColor', minLevel: CapabilityLevel.advanced, label: 'Border colour'),
  PropertyMeta(key: 'shadowColor', minLevel: CapabilityLevel.advanced, label: 'Shadow colour'),
  PropertyMeta(key: 'shadowBlur', minLevel: CapabilityLevel.advanced, label: 'Shadow blur'),
  PropertyMeta(key: 'shadowOffsetY', minLevel: CapabilityLevel.advanced, label: 'Shadow offset Y'),
  PropertyMeta(key: 'opacity', minLevel: CapabilityLevel.advanced, label: 'Opacity'),
  PropertyMeta(key: 'padding', minLevel: CapabilityLevel.basic, label: 'Padding', safe: true),
  PropertyMeta(key: 'width', minLevel: CapabilityLevel.basic, label: 'Width', safe: true),
  PropertyMeta(key: 'height', minLevel: CapabilityLevel.basic, label: 'Height', safe: true),
  PropertyMeta(key: 'visible', minLevel: CapabilityLevel.basic, label: 'Visible', safe: true),
];

const List<PropertyMeta> _status = [
  PropertyMeta(key: 'fault', minLevel: CapabilityLevel.advanced, label: 'Fault binding'),
  PropertyMeta(key: 'label', minLevel: CapabilityLevel.basic, label: 'Label', safe: true),
  PropertyMeta(key: 'value', minLevel: CapabilityLevel.advanced, label: 'State text'),
  PropertyMeta(key: 'backgroundColor', minLevel: CapabilityLevel.basic, label: 'Background', safe: true),
  PropertyMeta(key: 'borderRadius', minLevel: CapabilityLevel.advanced, label: 'Corner radius'),
  PropertyMeta(key: 'fontSize', minLevel: CapabilityLevel.basic, label: 'Font size', safe: true),
  PropertyMeta(key: 'borderWidth', minLevel: CapabilityLevel.advanced, label: 'Border width'),
  PropertyMeta(key: 'borderColor', minLevel: CapabilityLevel.advanced, label: 'Border colour'),
  PropertyMeta(key: 'shadowColor', minLevel: CapabilityLevel.advanced, label: 'Shadow colour'),
  PropertyMeta(key: 'shadowBlur', minLevel: CapabilityLevel.advanced, label: 'Shadow blur'),
  PropertyMeta(key: 'shadowOffsetY', minLevel: CapabilityLevel.advanced, label: 'Shadow offset Y'),
  PropertyMeta(key: 'opacity', minLevel: CapabilityLevel.advanced, label: 'Opacity'),
  PropertyMeta(key: 'padding', minLevel: CapabilityLevel.basic, label: 'Padding', safe: true),
  PropertyMeta(key: 'width', minLevel: CapabilityLevel.basic, label: 'Width', safe: true),
  PropertyMeta(key: 'height', minLevel: CapabilityLevel.basic, label: 'Height', safe: true),
  PropertyMeta(key: 'visible', minLevel: CapabilityLevel.basic, label: 'Visible', safe: true),
];

const List<PropertyMeta> _chart = [
  PropertyMeta(key: 'value', minLevel: CapabilityLevel.advanced, label: 'Value binding'),
  PropertyMeta(key: 'min', minLevel: CapabilityLevel.basic, label: 'Y minimum', safe: true),
  PropertyMeta(key: 'max', minLevel: CapabilityLevel.basic, label: 'Y maximum', safe: true),
  PropertyMeta(key: 'window', minLevel: CapabilityLevel.advanced, label: 'Sample window'),
  PropertyMeta(key: 'label', minLevel: CapabilityLevel.basic, label: 'Label', safe: true),
  PropertyMeta(key: 'unit', minLevel: CapabilityLevel.basic, label: 'Unit', safe: true),
  PropertyMeta(key: 'color', minLevel: CapabilityLevel.basic, label: 'Colour', safe: true),
  PropertyMeta(key: 'lineWidth', minLevel: CapabilityLevel.advanced, label: 'Line width'),
  PropertyMeta(key: 'showGrid', minLevel: CapabilityLevel.basic, label: 'Show grid', safe: true),
  PropertyMeta(key: 'gridColor', minLevel: CapabilityLevel.advanced, label: 'Grid colour'),
  PropertyMeta(key: 'smoothCurve', minLevel: CapabilityLevel.advanced, label: 'Smooth curve'),
  PropertyMeta(key: 'fillArea', minLevel: CapabilityLevel.advanced, label: 'Fill area'),
  PropertyMeta(key: 'fillColor', minLevel: CapabilityLevel.advanced, label: 'Fill colour'),
  PropertyMeta(key: 'backgroundColor', minLevel: CapabilityLevel.basic, label: 'Background', safe: true),
  PropertyMeta(key: 'borderRadius', minLevel: CapabilityLevel.advanced, label: 'Corner radius'),
  PropertyMeta(key: 'fontSize', minLevel: CapabilityLevel.basic, label: 'Font size', safe: true),
  PropertyMeta(key: 'borderWidth', minLevel: CapabilityLevel.advanced, label: 'Border width'),
  PropertyMeta(key: 'borderColor', minLevel: CapabilityLevel.advanced, label: 'Border colour'),
  PropertyMeta(key: 'shadowColor', minLevel: CapabilityLevel.advanced, label: 'Shadow colour'),
  PropertyMeta(key: 'shadowBlur', minLevel: CapabilityLevel.advanced, label: 'Shadow blur'),
  PropertyMeta(key: 'shadowOffsetY', minLevel: CapabilityLevel.advanced, label: 'Shadow offset Y'),
  PropertyMeta(key: 'opacity', minLevel: CapabilityLevel.advanced, label: 'Opacity'),
  PropertyMeta(key: 'padding', minLevel: CapabilityLevel.basic, label: 'Padding', safe: true),
  PropertyMeta(key: 'width', minLevel: CapabilityLevel.basic, label: 'Width', safe: true),
  PropertyMeta(key: 'height', minLevel: CapabilityLevel.basic, label: 'Height', safe: true),
  PropertyMeta(key: 'visible', minLevel: CapabilityLevel.basic, label: 'Visible', safe: true),
];

const List<PropertyMeta> _image = [
  PropertyMeta(key: 'src', minLevel: CapabilityLevel.basic, label: 'Image source', safe: true),
  PropertyMeta(key: 'fit', minLevel: CapabilityLevel.advanced, label: 'Fit mode'),
  PropertyMeta(key: 'tint', minLevel: CapabilityLevel.basic, label: 'Tint', safe: true),
  PropertyMeta(key: 'opacity', minLevel: CapabilityLevel.advanced, label: 'Opacity'),
  PropertyMeta(key: 'borderRadius', minLevel: CapabilityLevel.advanced, label: 'Corner radius'),
  PropertyMeta(key: 'borderWidth', minLevel: CapabilityLevel.advanced, label: 'Border width'),
  PropertyMeta(key: 'borderColor', minLevel: CapabilityLevel.advanced, label: 'Border colour'),
  PropertyMeta(key: 'shadowColor', minLevel: CapabilityLevel.advanced, label: 'Shadow colour'),
  PropertyMeta(key: 'shadowBlur', minLevel: CapabilityLevel.advanced, label: 'Shadow blur'),
  PropertyMeta(key: 'shadowOffsetY', minLevel: CapabilityLevel.advanced, label: 'Shadow offset Y'),
  PropertyMeta(key: 'padding', minLevel: CapabilityLevel.basic, label: 'Padding', safe: true),
  PropertyMeta(key: 'width', minLevel: CapabilityLevel.basic, label: 'Width', safe: true),
  PropertyMeta(key: 'height', minLevel: CapabilityLevel.basic, label: 'Height', safe: true),
];

const List<PropertyMeta> _web = [
  PropertyMeta(key: 'url', minLevel: CapabilityLevel.basic, label: 'URL', safe: true),
  PropertyMeta(key: 'title', minLevel: CapabilityLevel.basic, label: 'Title', safe: true),
  PropertyMeta(key: 'js', minLevel: CapabilityLevel.advanced, label: 'JavaScript enabled'),
  PropertyMeta(key: 'borderRadius', minLevel: CapabilityLevel.advanced, label: 'Corner radius'),
  PropertyMeta(key: 'borderWidth', minLevel: CapabilityLevel.advanced, label: 'Border width'),
  PropertyMeta(key: 'borderColor', minLevel: CapabilityLevel.advanced, label: 'Border colour'),
  PropertyMeta(key: 'shadowColor', minLevel: CapabilityLevel.advanced, label: 'Shadow colour'),
  PropertyMeta(key: 'shadowBlur', minLevel: CapabilityLevel.advanced, label: 'Shadow blur'),
  PropertyMeta(key: 'shadowOffsetY', minLevel: CapabilityLevel.advanced, label: 'Shadow offset Y'),
  PropertyMeta(key: 'padding', minLevel: CapabilityLevel.basic, label: 'Padding', safe: true),
  PropertyMeta(key: 'width', minLevel: CapabilityLevel.basic, label: 'Width', safe: true),
  PropertyMeta(key: 'height', minLevel: CapabilityLevel.basic, label: 'Height', safe: true),
  PropertyMeta(key: 'visible', minLevel: CapabilityLevel.basic, label: 'Visible', safe: true),
];

const List<PropertyMeta> _paint = [
  PropertyMeta(key: 'program', minLevel: CapabilityLevel.expert, label: 'Paint program (DSL)'),
];

const List<PropertyMeta> _digitalspeed = [
  PropertyMeta(key: 'value', minLevel: CapabilityLevel.advanced, label: 'Value binding'),
  PropertyMeta(key: 'unit', minLevel: CapabilityLevel.basic, label: 'Unit', safe: true),
  PropertyMeta(key: 'color', minLevel: CapabilityLevel.basic, label: 'Colour', safe: true),
  PropertyMeta(key: 'accent', minLevel: CapabilityLevel.advanced, label: 'Accent colour'),
  PropertyMeta(key: 'showUnit', minLevel: CapabilityLevel.basic, label: 'Show unit', safe: true),
  PropertyMeta(key: 'subLabel', minLevel: CapabilityLevel.basic, label: 'Sub-label', safe: true),
  PropertyMeta(key: 'subValue', minLevel: CapabilityLevel.advanced, label: 'Sub-value'),
  PropertyMeta(key: 'backgroundColor', minLevel: CapabilityLevel.basic, label: 'Background', safe: true),
  PropertyMeta(key: 'borderRadius', minLevel: CapabilityLevel.advanced, label: 'Corner radius'),
  PropertyMeta(key: 'fontSize', minLevel: CapabilityLevel.basic, label: 'Font size', safe: true),
  PropertyMeta(key: 'borderWidth', minLevel: CapabilityLevel.advanced, label: 'Border width'),
  PropertyMeta(key: 'borderColor', minLevel: CapabilityLevel.advanced, label: 'Border colour'),
  PropertyMeta(key: 'shadowColor', minLevel: CapabilityLevel.advanced, label: 'Shadow colour'),
  PropertyMeta(key: 'shadowBlur', minLevel: CapabilityLevel.advanced, label: 'Shadow blur'),
  PropertyMeta(key: 'shadowOffsetY', minLevel: CapabilityLevel.advanced, label: 'Shadow offset Y'),
  PropertyMeta(key: 'opacity', minLevel: CapabilityLevel.advanced, label: 'Opacity'),
  PropertyMeta(key: 'padding', minLevel: CapabilityLevel.basic, label: 'Padding', safe: true),
  PropertyMeta(key: 'width', minLevel: CapabilityLevel.basic, label: 'Width', safe: true),
  PropertyMeta(key: 'height', minLevel: CapabilityLevel.basic, label: 'Height', safe: true),
  PropertyMeta(key: 'visible', minLevel: CapabilityLevel.basic, label: 'Visible', safe: true),
];

const List<PropertyMeta> _music = [
  PropertyMeta(key: 'title', minLevel: CapabilityLevel.basic, label: 'Track title', safe: true),
  PropertyMeta(key: 'artist', minLevel: CapabilityLevel.basic, label: 'Artist', safe: true),
  PropertyMeta(key: 'album', minLevel: CapabilityLevel.advanced, label: 'Album'),
  PropertyMeta(key: 'progress', minLevel: CapabilityLevel.advanced, label: 'Progress (s)'),
  PropertyMeta(key: 'duration', minLevel: CapabilityLevel.advanced, label: 'Duration (s)'),
  PropertyMeta(key: 'showControls', minLevel: CapabilityLevel.basic, label: 'Show controls', safe: true),
  PropertyMeta(key: 'color', minLevel: CapabilityLevel.basic, label: 'Colour', safe: true),
  PropertyMeta(key: 'accent', minLevel: CapabilityLevel.advanced, label: 'Accent colour'),
  PropertyMeta(key: 'albumColor', minLevel: CapabilityLevel.advanced, label: 'Album art colour'),
  PropertyMeta(key: 'backgroundColor', minLevel: CapabilityLevel.basic, label: 'Background', safe: true),
  PropertyMeta(key: 'borderRadius', minLevel: CapabilityLevel.advanced, label: 'Corner radius'),
  PropertyMeta(key: 'fontSize', minLevel: CapabilityLevel.basic, label: 'Font size', safe: true),
  PropertyMeta(key: 'borderWidth', minLevel: CapabilityLevel.advanced, label: 'Border width'),
  PropertyMeta(key: 'borderColor', minLevel: CapabilityLevel.advanced, label: 'Border colour'),
  PropertyMeta(key: 'shadowColor', minLevel: CapabilityLevel.advanced, label: 'Shadow colour'),
  PropertyMeta(key: 'shadowBlur', minLevel: CapabilityLevel.advanced, label: 'Shadow blur'),
  PropertyMeta(key: 'shadowOffsetY', minLevel: CapabilityLevel.advanced, label: 'Shadow offset Y'),
  PropertyMeta(key: 'opacity', minLevel: CapabilityLevel.advanced, label: 'Opacity'),
  PropertyMeta(key: 'padding', minLevel: CapabilityLevel.basic, label: 'Padding', safe: true),
  PropertyMeta(key: 'width', minLevel: CapabilityLevel.basic, label: 'Width', safe: true),
  PropertyMeta(key: 'height', minLevel: CapabilityLevel.basic, label: 'Height', safe: true),
  PropertyMeta(key: 'visible', minLevel: CapabilityLevel.basic, label: 'Visible', safe: true),
];

const List<PropertyMeta> _tripstats = [
  PropertyMeta(key: 'label1', minLevel: CapabilityLevel.basic, label: 'Stat 1 label', safe: true),
  PropertyMeta(key: 'value1', minLevel: CapabilityLevel.advanced, label: 'Stat 1 value'),
  PropertyMeta(key: 'unit1', minLevel: CapabilityLevel.basic, label: 'Stat 1 unit', safe: true),
  PropertyMeta(key: 'label2', minLevel: CapabilityLevel.basic, label: 'Stat 2 label', safe: true),
  PropertyMeta(key: 'value2', minLevel: CapabilityLevel.advanced, label: 'Stat 2 value'),
  PropertyMeta(key: 'unit2', minLevel: CapabilityLevel.basic, label: 'Stat 2 unit', safe: true),
  PropertyMeta(key: 'label3', minLevel: CapabilityLevel.basic, label: 'Stat 3 label', safe: true),
  PropertyMeta(key: 'value3', minLevel: CapabilityLevel.advanced, label: 'Stat 3 value'),
  PropertyMeta(key: 'unit3', minLevel: CapabilityLevel.basic, label: 'Stat 3 unit', safe: true),
  PropertyMeta(key: 'label4', minLevel: CapabilityLevel.basic, label: 'Stat 4 label', safe: true),
  PropertyMeta(key: 'value4', minLevel: CapabilityLevel.advanced, label: 'Stat 4 value'),
  PropertyMeta(key: 'unit4', minLevel: CapabilityLevel.basic, label: 'Stat 4 unit', safe: true),
  PropertyMeta(key: 'columns', minLevel: CapabilityLevel.basic, label: 'Columns', safe: true),
  PropertyMeta(key: 'color', minLevel: CapabilityLevel.basic, label: 'Colour', safe: true),
  PropertyMeta(key: 'accent', minLevel: CapabilityLevel.advanced, label: 'Accent colour'),
  PropertyMeta(key: 'backgroundColor', minLevel: CapabilityLevel.basic, label: 'Background', safe: true),
  PropertyMeta(key: 'borderRadius', minLevel: CapabilityLevel.advanced, label: 'Corner radius'),
  PropertyMeta(key: 'fontSize', minLevel: CapabilityLevel.basic, label: 'Font size', safe: true),
  PropertyMeta(key: 'borderWidth', minLevel: CapabilityLevel.advanced, label: 'Border width'),
  PropertyMeta(key: 'borderColor', minLevel: CapabilityLevel.advanced, label: 'Border colour'),
  PropertyMeta(key: 'shadowColor', minLevel: CapabilityLevel.advanced, label: 'Shadow colour'),
  PropertyMeta(key: 'shadowBlur', minLevel: CapabilityLevel.advanced, label: 'Shadow blur'),
  PropertyMeta(key: 'shadowOffsetY', minLevel: CapabilityLevel.advanced, label: 'Shadow offset Y'),
  PropertyMeta(key: 'opacity', minLevel: CapabilityLevel.advanced, label: 'Opacity'),
  PropertyMeta(key: 'padding', minLevel: CapabilityLevel.basic, label: 'Padding', safe: true),
  PropertyMeta(key: 'width', minLevel: CapabilityLevel.basic, label: 'Width', safe: true),
  PropertyMeta(key: 'height', minLevel: CapabilityLevel.basic, label: 'Height', safe: true),
  PropertyMeta(key: 'visible', minLevel: CapabilityLevel.basic, label: 'Visible', safe: true),
];

const List<PropertyMeta> _power = [
  PropertyMeta(key: 'power', minLevel: CapabilityLevel.advanced, label: 'Power binding'),
  PropertyMeta(key: 'maxPower', minLevel: CapabilityLevel.basic, label: 'Max power', safe: true),
  PropertyMeta(key: 'regen', minLevel: CapabilityLevel.advanced, label: 'Regen binding'),
  PropertyMeta(key: 'maxRegen', minLevel: CapabilityLevel.basic, label: 'Max regen', safe: true),
  PropertyMeta(key: 'color', minLevel: CapabilityLevel.basic, label: 'Power colour', safe: true),
  PropertyMeta(key: 'regenColor', minLevel: CapabilityLevel.advanced, label: 'Regen colour'),
  PropertyMeta(key: 'accent', minLevel: CapabilityLevel.advanced, label: 'Accent colour'),
  PropertyMeta(key: 'showBars', minLevel: CapabilityLevel.basic, label: 'Show bars', safe: true),
  PropertyMeta(key: 'label', minLevel: CapabilityLevel.basic, label: 'Label', safe: true),
  PropertyMeta(key: 'backgroundColor', minLevel: CapabilityLevel.basic, label: 'Background', safe: true),
  PropertyMeta(key: 'borderRadius', minLevel: CapabilityLevel.advanced, label: 'Corner radius'),
  PropertyMeta(key: 'fontSize', minLevel: CapabilityLevel.basic, label: 'Font size', safe: true),
  PropertyMeta(key: 'borderWidth', minLevel: CapabilityLevel.advanced, label: 'Border width'),
  PropertyMeta(key: 'borderColor', minLevel: CapabilityLevel.advanced, label: 'Border colour'),
  PropertyMeta(key: 'shadowColor', minLevel: CapabilityLevel.advanced, label: 'Shadow colour'),
  PropertyMeta(key: 'shadowBlur', minLevel: CapabilityLevel.advanced, label: 'Shadow blur'),
  PropertyMeta(key: 'shadowOffsetY', minLevel: CapabilityLevel.advanced, label: 'Shadow offset Y'),
  PropertyMeta(key: 'opacity', minLevel: CapabilityLevel.advanced, label: 'Opacity'),
  PropertyMeta(key: 'padding', minLevel: CapabilityLevel.basic, label: 'Padding', safe: true),
  PropertyMeta(key: 'width', minLevel: CapabilityLevel.basic, label: 'Width', safe: true),
  PropertyMeta(key: 'height', minLevel: CapabilityLevel.basic, label: 'Height', safe: true),
  PropertyMeta(key: 'visible', minLevel: CapabilityLevel.basic, label: 'Visible', safe: true),
];

const List<PropertyMeta> _warnings = [
  PropertyMeta(key: 'activeWarnings', minLevel: CapabilityLevel.advanced, label: 'Active warnings'),
  PropertyMeta(key: 'color', minLevel: CapabilityLevel.basic, label: 'Error colour', safe: true),
  PropertyMeta(key: 'warningColor', minLevel: CapabilityLevel.advanced, label: 'Warning colour'),
  PropertyMeta(key: 'infoColor', minLevel: CapabilityLevel.advanced, label: 'Info colour'),
  PropertyMeta(key: 'iconSize', minLevel: CapabilityLevel.basic, label: 'Icon size', safe: true),
  PropertyMeta(key: 'backgroundColor', minLevel: CapabilityLevel.basic, label: 'Background', safe: true),
  PropertyMeta(key: 'borderRadius', minLevel: CapabilityLevel.advanced, label: 'Corner radius'),
  PropertyMeta(key: 'borderWidth', minLevel: CapabilityLevel.advanced, label: 'Border width'),
  PropertyMeta(key: 'borderColor', minLevel: CapabilityLevel.advanced, label: 'Border colour'),
  PropertyMeta(key: 'shadowColor', minLevel: CapabilityLevel.advanced, label: 'Shadow colour'),
  PropertyMeta(key: 'shadowBlur', minLevel: CapabilityLevel.advanced, label: 'Shadow blur'),
  PropertyMeta(key: 'shadowOffsetY', minLevel: CapabilityLevel.advanced, label: 'Shadow offset Y'),
  PropertyMeta(key: 'opacity', minLevel: CapabilityLevel.advanced, label: 'Opacity'),
  PropertyMeta(key: 'padding', minLevel: CapabilityLevel.basic, label: 'Padding', safe: true),
  PropertyMeta(key: 'width', minLevel: CapabilityLevel.basic, label: 'Width', safe: true),
  PropertyMeta(key: 'height', minLevel: CapabilityLevel.basic, label: 'Height', safe: true),
  PropertyMeta(key: 'visible', minLevel: CapabilityLevel.basic, label: 'Visible', safe: true),
];

const List<PropertyMeta> _minigauge = [
  PropertyMeta(key: 'value', minLevel: CapabilityLevel.advanced, label: 'Value binding'),
  PropertyMeta(key: 'min', minLevel: CapabilityLevel.basic, label: 'Minimum', safe: true),
  PropertyMeta(key: 'max', minLevel: CapabilityLevel.basic, label: 'Maximum', safe: true),
  PropertyMeta(key: 'label', minLevel: CapabilityLevel.basic, label: 'Label', safe: true),
  PropertyMeta(key: 'unit', minLevel: CapabilityLevel.basic, label: 'Unit', safe: true),
  PropertyMeta(key: 'icon', minLevel: CapabilityLevel.basic, label: 'Icon', safe: true),
  PropertyMeta(key: 'style', minLevel: CapabilityLevel.basic, label: 'Style', safe: true),
  PropertyMeta(key: 'color', minLevel: CapabilityLevel.basic, label: 'Colour', safe: true),
  PropertyMeta(key: 'accent', minLevel: CapabilityLevel.advanced, label: 'Accent colour'),
  PropertyMeta(key: 'backgroundColor', minLevel: CapabilityLevel.basic, label: 'Background', safe: true),
  PropertyMeta(key: 'borderRadius', minLevel: CapabilityLevel.advanced, label: 'Corner radius'),
  PropertyMeta(key: 'fontSize', minLevel: CapabilityLevel.basic, label: 'Font size', safe: true),
  PropertyMeta(key: 'borderWidth', minLevel: CapabilityLevel.advanced, label: 'Border width'),
  PropertyMeta(key: 'borderColor', minLevel: CapabilityLevel.advanced, label: 'Border colour'),
  PropertyMeta(key: 'shadowColor', minLevel: CapabilityLevel.advanced, label: 'Shadow colour'),
  PropertyMeta(key: 'shadowBlur', minLevel: CapabilityLevel.advanced, label: 'Shadow blur'),
  PropertyMeta(key: 'shadowOffsetY', minLevel: CapabilityLevel.advanced, label: 'Shadow offset Y'),
  PropertyMeta(key: 'opacity', minLevel: CapabilityLevel.advanced, label: 'Opacity'),
  PropertyMeta(key: 'padding', minLevel: CapabilityLevel.basic, label: 'Padding', safe: true),
  PropertyMeta(key: 'width', minLevel: CapabilityLevel.basic, label: 'Width', safe: true),
  PropertyMeta(key: 'height', minLevel: CapabilityLevel.basic, label: 'Height', safe: true),
  PropertyMeta(key: 'visible', minLevel: CapabilityLevel.basic, label: 'Visible', safe: true),
];

const List<PropertyMeta> _appgrid = [
  PropertyMeta(key: 'apps', minLevel: CapabilityLevel.basic, label: 'Apps list', safe: true),
  PropertyMeta(key: 'columns', minLevel: CapabilityLevel.basic, label: 'Columns', safe: true),
  PropertyMeta(key: 'iconSize', minLevel: CapabilityLevel.basic, label: 'Icon size', safe: true),
  PropertyMeta(key: 'showLabels', minLevel: CapabilityLevel.basic, label: 'Show labels', safe: true),
  PropertyMeta(key: 'color', minLevel: CapabilityLevel.basic, label: 'Colour', safe: true),
  PropertyMeta(key: 'accent', minLevel: CapabilityLevel.advanced, label: 'Accent colour'),
  PropertyMeta(key: 'backgroundColor', minLevel: CapabilityLevel.basic, label: 'Background', safe: true),
  PropertyMeta(key: 'borderRadius', minLevel: CapabilityLevel.advanced, label: 'Corner radius'),
  PropertyMeta(key: 'fontSize', minLevel: CapabilityLevel.basic, label: 'Font size', safe: true),
  PropertyMeta(key: 'borderWidth', minLevel: CapabilityLevel.advanced, label: 'Border width'),
  PropertyMeta(key: 'borderColor', minLevel: CapabilityLevel.advanced, label: 'Border colour'),
  PropertyMeta(key: 'shadowColor', minLevel: CapabilityLevel.advanced, label: 'Shadow colour'),
  PropertyMeta(key: 'shadowBlur', minLevel: CapabilityLevel.advanced, label: 'Shadow blur'),
  PropertyMeta(key: 'shadowOffsetY', minLevel: CapabilityLevel.advanced, label: 'Shadow offset Y'),
  PropertyMeta(key: 'opacity', minLevel: CapabilityLevel.advanced, label: 'Opacity'),
  PropertyMeta(key: 'padding', minLevel: CapabilityLevel.basic, label: 'Padding', safe: true),
  PropertyMeta(key: 'width', minLevel: CapabilityLevel.basic, label: 'Width', safe: true),
  PropertyMeta(key: 'height', minLevel: CapabilityLevel.basic, label: 'Height', safe: true),
  PropertyMeta(key: 'visible', minLevel: CapabilityLevel.basic, label: 'Visible', safe: true),
];

const List<PropertyMeta> _statusbar = [
  PropertyMeta(key: 'time', minLevel: CapabilityLevel.basic, label: 'Time', safe: true),
  PropertyMeta(key: 'battery', minLevel: CapabilityLevel.advanced, label: 'Battery level'),
  PropertyMeta(key: 'signal', minLevel: CapabilityLevel.advanced, label: 'Signal level'),
  PropertyMeta(key: 'showTime', minLevel: CapabilityLevel.basic, label: 'Show time', safe: true),
  PropertyMeta(key: 'showBattery', minLevel: CapabilityLevel.basic, label: 'Show battery', safe: true),
  PropertyMeta(key: 'showSignal', minLevel: CapabilityLevel.basic, label: 'Show signal', safe: true),
  PropertyMeta(key: 'color', minLevel: CapabilityLevel.basic, label: 'Colour', safe: true),
  PropertyMeta(key: 'accent', minLevel: CapabilityLevel.advanced, label: 'Accent colour'),
  PropertyMeta(key: 'backgroundColor', minLevel: CapabilityLevel.basic, label: 'Background', safe: true),
  PropertyMeta(key: 'borderRadius', minLevel: CapabilityLevel.advanced, label: 'Corner radius'),
  PropertyMeta(key: 'fontSize', minLevel: CapabilityLevel.basic, label: 'Font size', safe: true),
  PropertyMeta(key: 'borderWidth', minLevel: CapabilityLevel.advanced, label: 'Border width'),
  PropertyMeta(key: 'borderColor', minLevel: CapabilityLevel.advanced, label: 'Border colour'),
  PropertyMeta(key: 'shadowColor', minLevel: CapabilityLevel.advanced, label: 'Shadow colour'),
  PropertyMeta(key: 'shadowBlur', minLevel: CapabilityLevel.advanced, label: 'Shadow blur'),
  PropertyMeta(key: 'shadowOffsetY', minLevel: CapabilityLevel.advanced, label: 'Shadow offset Y'),
  PropertyMeta(key: 'opacity', minLevel: CapabilityLevel.advanced, label: 'Opacity'),
  PropertyMeta(key: 'padding', minLevel: CapabilityLevel.basic, label: 'Padding', safe: true),
  PropertyMeta(key: 'width', minLevel: CapabilityLevel.basic, label: 'Width', safe: true),
  PropertyMeta(key: 'height', minLevel: CapabilityLevel.basic, label: 'Height', safe: true),
  PropertyMeta(key: 'visible', minLevel: CapabilityLevel.basic, label: 'Visible', safe: true),
];

const List<PropertyMeta> _climate = [
  PropertyMeta(key: 'temperature', minLevel: CapabilityLevel.advanced, label: 'Temperature'),
  PropertyMeta(key: 'targetTemp', minLevel: CapabilityLevel.advanced, label: 'Target temperature'),
  PropertyMeta(key: 'fanSpeed', minLevel: CapabilityLevel.advanced, label: 'Fan speed'),
  PropertyMeta(key: 'mode', minLevel: CapabilityLevel.basic, label: 'Mode', safe: true),
  PropertyMeta(key: 'unit', minLevel: CapabilityLevel.basic, label: 'Unit', safe: true),
  PropertyMeta(key: 'color', minLevel: CapabilityLevel.basic, label: 'Colour', safe: true),
  PropertyMeta(key: 'accent', minLevel: CapabilityLevel.advanced, label: 'Accent colour'),
  PropertyMeta(key: 'backgroundColor', minLevel: CapabilityLevel.basic, label: 'Background', safe: true),
  PropertyMeta(key: 'borderRadius', minLevel: CapabilityLevel.advanced, label: 'Corner radius'),
  PropertyMeta(key: 'fontSize', minLevel: CapabilityLevel.basic, label: 'Font size', safe: true),
  PropertyMeta(key: 'borderWidth', minLevel: CapabilityLevel.advanced, label: 'Border width'),
  PropertyMeta(key: 'borderColor', minLevel: CapabilityLevel.advanced, label: 'Border colour'),
  PropertyMeta(key: 'shadowColor', minLevel: CapabilityLevel.advanced, label: 'Shadow colour'),
  PropertyMeta(key: 'shadowBlur', minLevel: CapabilityLevel.advanced, label: 'Shadow blur'),
  PropertyMeta(key: 'shadowOffsetY', minLevel: CapabilityLevel.advanced, label: 'Shadow offset Y'),
  PropertyMeta(key: 'opacity', minLevel: CapabilityLevel.advanced, label: 'Opacity'),
  PropertyMeta(key: 'padding', minLevel: CapabilityLevel.basic, label: 'Padding', safe: true),
  PropertyMeta(key: 'width', minLevel: CapabilityLevel.basic, label: 'Width', safe: true),
  PropertyMeta(key: 'height', minLevel: CapabilityLevel.basic, label: 'Height', safe: true),
  PropertyMeta(key: 'visible', minLevel: CapabilityLevel.basic, label: 'Visible', safe: true),
];

const List<PropertyMeta> _car_viz = [
  PropertyMeta(key: 'laneLeft', minLevel: CapabilityLevel.advanced, label: 'Left lane warning'),
  PropertyMeta(key: 'laneRight', minLevel: CapabilityLevel.advanced, label: 'Right lane warning'),
  PropertyMeta(key: 'carAhead', minLevel: CapabilityLevel.advanced, label: 'Car ahead'),
  PropertyMeta(key: 'label', minLevel: CapabilityLevel.basic, label: 'Label', safe: true),
  PropertyMeta(key: 'color', minLevel: CapabilityLevel.basic, label: 'Colour', safe: true),
  PropertyMeta(key: 'accent', minLevel: CapabilityLevel.advanced, label: 'Accent colour'),
  PropertyMeta(key: 'backgroundColor', minLevel: CapabilityLevel.basic, label: 'Background', safe: true),
  PropertyMeta(key: 'borderRadius', minLevel: CapabilityLevel.advanced, label: 'Corner radius'),
  PropertyMeta(key: 'borderWidth', minLevel: CapabilityLevel.advanced, label: 'Border width'),
  PropertyMeta(key: 'borderColor', minLevel: CapabilityLevel.advanced, label: 'Border colour'),
  PropertyMeta(key: 'shadowColor', minLevel: CapabilityLevel.advanced, label: 'Shadow colour'),
  PropertyMeta(key: 'shadowBlur', minLevel: CapabilityLevel.advanced, label: 'Shadow blur'),
  PropertyMeta(key: 'shadowOffsetY', minLevel: CapabilityLevel.advanced, label: 'Shadow offset Y'),
  PropertyMeta(key: 'opacity', minLevel: CapabilityLevel.advanced, label: 'Opacity'),
  PropertyMeta(key: 'padding', minLevel: CapabilityLevel.basic, label: 'Padding', safe: true),
  PropertyMeta(key: 'width', minLevel: CapabilityLevel.basic, label: 'Width', safe: true),
  PropertyMeta(key: 'height', minLevel: CapabilityLevel.basic, label: 'Height', safe: true),
  PropertyMeta(key: 'visible', minLevel: CapabilityLevel.basic, label: 'Visible', safe: true),
];

const List<PropertyMeta> _map = [
  PropertyMeta(key: 'label', minLevel: CapabilityLevel.basic, label: 'Label', safe: true),
  PropertyMeta(key: 'eta', minLevel: CapabilityLevel.advanced, label: 'ETA'),
  PropertyMeta(key: 'distance', minLevel: CapabilityLevel.advanced, label: 'Distance'),
  PropertyMeta(key: 'nextTurn', minLevel: CapabilityLevel.advanced, label: 'Next turn'),
  PropertyMeta(key: 'color', minLevel: CapabilityLevel.basic, label: 'Colour', safe: true),
  PropertyMeta(key: 'accent', minLevel: CapabilityLevel.advanced, label: 'Accent colour'),
  PropertyMeta(key: 'backgroundColor', minLevel: CapabilityLevel.basic, label: 'Background', safe: true),
  PropertyMeta(key: 'borderRadius', minLevel: CapabilityLevel.advanced, label: 'Corner radius'),
  PropertyMeta(key: 'borderWidth', minLevel: CapabilityLevel.advanced, label: 'Border width'),
  PropertyMeta(key: 'borderColor', minLevel: CapabilityLevel.advanced, label: 'Border colour'),
  PropertyMeta(key: 'shadowColor', minLevel: CapabilityLevel.advanced, label: 'Shadow colour'),
  PropertyMeta(key: 'shadowBlur', minLevel: CapabilityLevel.advanced, label: 'Shadow blur'),
  PropertyMeta(key: 'shadowOffsetY', minLevel: CapabilityLevel.advanced, label: 'Shadow offset Y'),
  PropertyMeta(key: 'opacity', minLevel: CapabilityLevel.advanced, label: 'Opacity'),
  PropertyMeta(key: 'padding', minLevel: CapabilityLevel.basic, label: 'Padding', safe: true),
  PropertyMeta(key: 'width', minLevel: CapabilityLevel.basic, label: 'Width', safe: true),
  PropertyMeta(key: 'height', minLevel: CapabilityLevel.basic, label: 'Height', safe: true),
  PropertyMeta(key: 'visible', minLevel: CapabilityLevel.basic, label: 'Visible', safe: true),
];

const Map<String, List<PropertyMeta>> propertyManifest = {
  'gauge': _gauge,
  'bar': _bar,
  'text': _text,
  'status': _status,
  'chart': _chart,
  'image': _image,
  'web': _web,
  'paint': _paint,
  'digitalspeed': _digitalspeed,
  'music': _music,
  'tripstats': _tripstats,
  'power': _power,
  'warnings': _warnings,
  'minigauge': _minigauge,
  'appgrid': _appgrid,
  'statusbar': _statusbar,
  'climate': _climate,
  'car_viz': _car_viz,
  'map': _map,
};

List<PropertyMeta> visibleProperties(String widgetKind, CapabilityLevel level) {
  final manifest = propertyManifest[widgetKind] ?? const <PropertyMeta>[];
  return manifest.where((m) => level.includes(m.minLevel)).toList();
}

List<PropertyMeta> allProperties(String widgetKind) {
  return (propertyManifest[widgetKind] ?? const <PropertyMeta>[]).toList();
}

bool transformsUnlockedAt(CapabilityLevel level) =>
    level.index >= CapabilityLevel.advanced.index;
